### ISSUE TITLE
router seems dead. class is loading fine

### ISSUE THREAD

**Issue by ottonascarella** [dannyvankooten/AltoRouter#101]
hi people!

Please enlighten me on something:

```
ini_set('display_startup_errors',1);
ini_set('display_errors',1);
error_reporting(-1);

$router = new AltoRouter();
$router->map("GET","*", function() {
	echo "BOOM!";
});

```
I am not getting any BOOM...nor any errors!
Why?

**Comment by dannyvankooten** [comment]
Hi there, 

You should call the match method (see "match requests" on AltoRouter site) for the router to evaluate the current request.

Also, you should probably use `/*`. It's been a while and I am on mobile so not super sure on that last one. :-)

**Comment by ottonascarella** [comment]
with that it worked.
cheers.



On 28 January 2015 at 14:56, Danny van Kooten <notifications@github.com>
wrote:

> Hi there,
>
> You should call the match method (see "match requests" on AltoRouter site)
> for the router to evaluate the current request.
>
> Also, you should probably use /*. It's been a while and I am on mobile so
> not super sure on that last one. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dannyvankooten/AltoRouter/issues/101#issuecomment-71871230>
> .
>



-- 

Otto Nascarella
+55 21 3496 8566
+55 21 98013 3944

**Comment by dannyvankooten** [comment]
:+1: Awesome!
