### ISSUE TITLE
Redirect from www to non www

### ISSUE THREAD

**Issue by IOZ** [dannyvankooten/AltoRouter#102]
Hi Danny,

could you update doc "Rewrite all requests to AltoRouter"
and put there information how to redirect site from www to non www
using existing conditions.

For e.g using next approach
```
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [R=301,L]
```

Cheers,
Igor.

**Comment by koenpunt** [comment]
Redirection is outside of the scope of AltoRouter if you ask me..

**Comment by dannyvankooten** [comment]
Hey @IOZ , I definitely agree with @koenpunt on this one. AltoRouter shouldn't care whichever subdomain it's running on. Thank you for your suggestion though! :smiley:
