### ISSUE TITLE
$_REQUEST is unused

### ISSUE THREAD

**Issue by koenpunt** [dannyvankooten/AltoRouter#104]
On [line 175](https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L175) `$_REQUEST` is being set to a combination of `$_GET` and `$_POST`, but `$_REQUEST` isn't used anywhere in the script.

Noticed this while processing the codeclimate issues.

**Comment by koenpunt** [comment]
@dannyvankooten Any thoughts on this?

**Comment by stickypages** [comment]
I noticed the same thing, perhaps add it to the return array()?

ie: return array(
					'target' => $target,
					'params' => $params,
					'name' => $name,
					'req'  => $_REQUEST
				);

**Comment by koenpunt** [comment]
There's no use in passing a global variable along, because it can be can be accessed globally anyways.

**Comment by dannyvankooten** [comment]
Sorry for the absence all. To be honest, I don't think the `$_REQUEST` global was ever used, it's some leftover code from before the first commit.

We shouldn't mess with _any_ globals in my opinion so definitely eager to remove it. :)

**Comment by koenpunt** [comment]
Speaking of leftover code, what about #100 ? 😄
