### ISSUE TITLE
Dot is not matched

### ISSUE THREAD

**Issue by alexschwarz89** [dannyvankooten/AltoRouter#108]
Example/[:url]/   should match   http://myapi/Example/example.com/

But it does not. If I write "examplecom" (without dot), it matches.
Shouldn't [:something] match all to the next "/"  or end of URI?

Best regards

**Comment by koenpunt** [comment]
`Example/[:url]/` excludes dots. (see: [AltoRouter.php#L14](https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L14))

Using `*` makes the match more greedy: `Example/[*:url]/`  ([AltoRouter.php#L12](https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L12))
