### ISSUE TITLE
Getting a blank page

### ISSUE THREAD

**Issue by digitalcraftstudios** [dannyvankooten/AltoRouter#109]
Hi,
I'm getting a blank page while mapping requests, see:   
index.php:

    require 'vendor/autoload.php';
    $router = new AltoRouter();
    $router->map('GET', '/', function() {
    require __DIR__ . '/views/home.php';    
    echo "it is working";
    },'home');

I also tried calling the `$router->generate('home');` method but no luck.
It's quite surprising as there are no errors to help with debugging. 
Interestingly the echoed text inside the function doesn't even get printed.

My stack is LAMP (via MAMP Pro). Apache2, PHP5.5

Have you seen this before?

Thanks.

**Comment by dannyvankooten** [comment]
Hi there,

Please enable error_reporting in your PHP configuration, that'll save you many hours of headaches during development. :-)

**Comment by thatjoshguy** [comment]
i have error reporting on, having the same issue, there are no errors - is this library compatible with PHP 5.5?

**Comment by dannyvankooten** [comment]
It should definitely be, did you configure your server correctly? It should
forward all URL's to your AltoRouter file..

**Comment by eBerdnA** [comment]
I'm having the same issue using the code from the first message. No error just a HTTP 200 response from the server but no content at all. Furthermore no error.

Using your php-router works without any issue in the same environment.

Php:  5.5.15
Apache2: 2.4.10 (Win32)

if you need any further information just let me know.

**Comment by koenpunt** [comment]
Do you make a call to `$router->match()`?

**Comment by eBerdnA** [comment]
Yes I do but it makes no difference. I'm using the following code but it is basically the same as of @digitalcraftstudios.

```php
<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);   
require 'vendor/autoload.php';  
$router = new AltoRouter();  
$router->map('GET', '/', function() {  
  echo "it is working";  
},'home');  
$router->match();  
?>
```

**Comment by koenpunt** [comment]
`$router->match()` returns a value, and you'll have to do something with yourself. See the docs for an example: http://altorouter.com/usage/matching-requests.html

**Comment by koenpunt** [comment]
Practical example using your code:
```php
<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);   
require 'vendor/autoload.php';  
$router = new AltoRouter();  
$router->map('GET', '/', function() {  
  echo "it is working";  
},'home');  
$match = $router->match();  
if($match){
	call_user_func($match['target'], $match['params']);
}
?>

**Comment by eBerdnA** [comment]
Thanks for your explanation. Seems like I did not read the documentation carefully enough.
Your example is working fine. So from my point of view this issue could be closed.

**Comment by koenpunt** [comment]
@digitalcraftstudios does this resolve the issue for you as well?
