### ISSUE TITLE
Add return parameters

### ISSUE THREAD

**Issue by visavi** [dannyvankooten/AltoRouter#110]
Why not add to the array method that returns a match
$requestUrl and $requestMethod to get something like this

return array(
'target' => $target,
'params' => $params,
'name' => $name,
'request_url' => $requestUrl,
'request_method' => $requestMethod,
);

sometimes more convenient to have a ready set of data than to calculate the page

And in general, why not return the array and not an object?

**Comment by koenpunt** [comment]
Please elaborate, what would be the use of this?

**Comment by visavi** [comment]
For example, I returned page via a router, for example I need to know reguest_url for release of the active tab,
not to initiate some new variables
and that they are set in a ready and can easily obtain the data

**Comment by koenpunt** [comment]
I think the use case is too specific. Is most cases a router is used to abstract the use of the raw url and request method.
