### ISSUE TITLE
Color hex Issue

### ISSUE THREAD

**Issue by moazam1** [dannyvankooten/AltoRouter#113]
I am trying to create a url for colors i.e. http://site.com/#ffffff and for that I have added a match type: 

`#([a-fA-F0-9]){3}(([a-fA-F0-9]){3})?\b` Altorouter is not is recognizing `#` in the regex. I tried to escape but it didn't work. Any help?

**Comment by niahoo** [comment]
Hi, 

Take a look at the network in the development tools, your browser is not sending the part of the URL after the `#`. Because it's a special character.

You must encode it, or simply drop it. why not just `/site/com/ffaa00` ?

**Comment by koenpunt** [comment]
Also, what are you trying to achieve?
