### ISSUE TITLE
Match routing url while send html form with GET method

### ISSUE THREAD

**Issue by tigitall** [dannyvankooten/AltoRouter#114]
Is it possible to populate URL with parameters send by html form with GET method?
In my FrontController:

```php
$oRouter = new AltoRouter();
$oRouter->map('GET|POST', '/find-agents/[:search_location]?', array('con' => 'agent', 'act' => 'find-agents'), 'agent@find-agents');
$match = $oRouter->match();
var_dump($match);

array (size=3)
  'target' => 
    array (size=2)
      'con' => string 'agent' (length=5)
      'act' => string 'find-agents' (length=11)
  'params' => 
    array (size=0)
      empty
  'name' => string 'agent@find-agents' (length=17)
```
In my action view:
```php
form name="findAgentsForm" method="get" action="<?php echo $this->getRouter()->generate('agent@find-agents'); ?>"

input type="text" name="search_location" value=""
```

search_location is optional parameter so the action in above form is "/find-agents" - this url just show the form

When I send the form with search_location input value I would like application to go to url "find-agents/entered-location" (this url would show form and search results) but instead I have url "find-agents?search_location=entered-location".

Thank you in advance for your help and sorry for my English.

**Comment by koenpunt** [comment]
This can only be achieved with the use of JavaScript. Create an onsubmit handler which stops the default submit and redirects the user to the form action URL with the query appended as path

**Comment by koenpunt** [comment]
Also, this has nothing to do with AltoRouter, so closing this.
