### ISSUE TITLE
URL Request isn't absolute

### ISSUE THREAD

**Issue by cynephoba** [dannyvankooten/AltoRouter#115]
When creating a URL request, it doesn't take your complete URL as the request. It gets matches from the URL in the order that they are mapped.

For example, if i have /login/ mapped to login.php and /home/ mapped to home.php (in that order),
so: 
**site.com/login/** shows login.php
**site.com/home/** shows home.php
**site.com/home/login/** shows login.php (since it's mapped first)
**site.com/gibberish/randomstuff/home** shows home.php (even though *gibberish* and *randomstuff* isn't mapped at all, so it should throw an error.)
but then:
**site.com/gibberish/randomstuff/login/home** will show login.php (because its mapped first, even though home was the last one on the URL)

Just wanting to work out a way to fix this problem 

Thanks!!

**Comment by mxdpeep** [comment]
this works for me as intended:

		$router = new \AltoRouter();
		$router->setBasePath('/api/v'.API_VERSION);
		$router->map('GET|POST', '/', 'api#index', 'api');
		$router->map('GET|POST', '/test/', 'api#test', 'test');
		$router->map('GET|POST', '/test/[i:id]', 'api#test#id', 'test_someid');
		$router->map('GET|POST', '/xxx/', 'api#xxx#test', '');
		$router->map('GET|POST', '/xxx/test', 'api#xxx#test', 'xxx_test');
		$router->map('GET|POST', '/xxx/[i:id]', 'api#xxx#id', 'xxx_id');

you can try here:

[https://app.mxd.cz/api/v1/test/1161](https://app.mxd.cz/api/v1/test/1161)

**Comment by koenpunt** [comment]
It depends on how you define your routes. For what I understand if your question without seeing your actual code is that you've defined your routes too loosely. 
I might be able to help you out if you post your code here as well

**Comment by cynephoba** [comment]
@koenpunt 

This is my code:


```PHP

$router->map('GET','/', 'homeview', 'SiteIndex'); //Home index page
$router->map('GET','@([Hh]ome[\\/]?)', 'homeView', 'Home'); //Home index page
$router->map('GET','@([Ll]ogin[\\/]?)', 'loginView', 'Login'); //Login page
$router->map('GET','@([Rr]egister[\\/]?)', 'registerView', 'Register'); //Register page
$router->map('GET','@([Aa]boutus[\\/]?)', 'aboutus.php', 'AboutUs'); //Contact Us page
$router->map('GET', '@([Aa]dmin[\\/]?)', 'adminView', 'Admin'); //Admin page
```

**Comment by koenpunt** [comment]
Like I said, your routes are set up too loosely, try the following:

```php
$router->map('GET','/', 'homeview', 'SiteIndex'); //Home index page
$router->map('GET','@\\/([Hh]ome[\\/]?)', 'homeView', 'Home'); //Home index page
$router->map('GET','@\\/([Ll]ogin[\\/]?)', 'loginView', 'Login'); //Login page
$router->map('GET','@\\/([Rr]egister[\\/]?)', 'registerView', 'Register'); //Register page
$router->map('GET','@\\/([Aa]boutus[\\/]?)', 'aboutus.php', 'AboutUs'); //Contact Us page
$router->map('GET', '@\\/([Aa]dmin[\\/]?)', 'adminView', 'Admin'); //Admin page
```

**Comment by cynephoba** [comment]
Still no luck. It still has the issue that I posted above, and also misspellings in the URL still map (IE having site.com/registerrrrrrr/ maps to register because you still have the word register in there).

**Comment by koenpunt** [comment]
Ok, but this is not an issue with AltoRouter. You'll just have to tweak your regular expressions a bit

**Comment by cynephoba** [comment]
My expressions are only checking for capitals and slashes...that shouldn't allow for random stuff in the URLs still mapping to pages like I said in the original post. How is that not an issue with altorouter?

**Comment by cynephoba** [comment]
I'm not sure how it is not an issue with AltoRouter. Using your routes exactly it is still giving me the issue. I have a valid regex string.
The problem is that you're only matching part of the URL with the regex not the full URL - and therefore because of that it still redirects it when it shouldn't (or so it seems). Therefore still an issue with AltoRouter?

**Comment by mxdpeep** [comment]
have you set $router->setBasePath ??

**Comment by cynephoba** [comment]
Yea it's set and working fine, it just matches URLs it shouldn't ("registerrrrrAaaaa" to "register" because it contains the word etc)

**Comment by koenpunt** [comment]
If you want to match the full url, you'll have to add delimiters; `^` and `$`

**Comment by mxdpeep** [comment]
yes, add ^ for the start and $ for the end of RegExp
