### ISSUE TITLE
How can I allow a slash parameter in my URL?

### ISSUE THREAD

**Issue by JonBlue** [dannyvankooten/AltoRouter#117]
I'm playing around with a directory scanner and I need to pass the path to folder/files as a GET parameter.

example `dirscan/Full/Path/to-file`

I need to call the controller, dirscan, and have everything else passed as a parameter named, let's say, path.

Any help?

**Comment by koenpunt** [comment]
If I recall correctly this should do the trick:
```php
$router->map('GET', '/dirscan[**:path]');
```
The double `*` is super-greedy
