### ISSUE TITLE
Getting started page leads to belkin router page

### ISSUE THREAD

**Issue by Superpat** [dannyvankooten/AltoRouter#119]
For some reason if I click on the various more info links, my browsers (I've tested with firefox and chrome) are unable to open the pages. And if I go to altorouter.com I seem to fall on a belkin router management page (I dont own a belkin).

**Comment by adduc** [comment]
Are you sure you're on the right network? <http://altorouter.com> is being served by Github, and there are currently no known issues with Github pages.

**Comment by Superpat** [comment]
Not sure why but when I click on that link it just brings me to the belkin router page, first time I have this problem.
