### ISSUE TITLE
how to read my optional parameter in class ?

### ISSUE THREAD

**Issue by concept-core** [dannyvankooten/AltoRouter#121]
Hello,

I am making a login api for my website which I can use with my ajax calls.
Now I want to make a optional parameter that will check if it is an api call or not.

For now I have the following : 
[code] <?php
	'login' 	=> array("GET|POST", "/user/login/[:api]?", "User#login"), // This is getting rendered afterwards.

// Class
	/**
	 * Log the user in
	 * @param  array $rawData array with post data
	 * @return string          returns an error if not found/matches.
	 */
	public function login($rawData) {
		var_dump($match); // how to get the matched parameter.

		if (isset($_POST['action'])) {
			$rawData = $_POST;
			$post = $this->a->login($rawData);
		} else {
			$post = null;
		}

		if($api == true) {
			return $post;
		}

		$this->template()->make('User/Login', array(
			'post'=>$post
		));
	}

?>[/code]

I can make a full example tomorrow.

**Comment by YannickFricke** [comment]
Please write more about your issue. I currently can't understand what you want to achieve. :)

**Comment by concept-core** [comment]
Hello I am trying to do a ajax login to the following url : http://localhost/user/login/[api] << optional

Now I have put in a optional parameter : [api].
So whenever I make a ajax call I want to use my optional so I make sure it comes from a api call.
And in the controller I want to check if that [api] parameter is set.

How can I do this the best with altorouter ?

Hopefully you understand it now :)

**Comment by concept-core** [comment]
Sorry got it working already.
