### ISSUE TITLE
static class ?

### ISSUE THREAD

**Issue by concept-core** [dannyvankooten/AltoRouter#122]
Hello everyone,

Is it an idea to make altorouter static ? 
The reason why I ask this is because I need to use it as a static class but it is not possible yet.

best regards,
Wouter

**Comment by koenpunt** [comment]
Why would you need it as a static class?

**Comment by dannyvankooten** [comment]
What @koenpunt says. I don't see why you would need it as a static class. If you don't need more than one instance, you can just create one and be done with it. Right? :smile:

**Comment by concept-core** [comment]
Well I cannot call a instance of it in my blade views.
Which would be awesome if I want to use the router.

But never mind I will create a child class that acts like a static.

**Comment by bizbink** [comment]
Why not dependency injection?

**Comment by concept-core** [comment]
nah figured it out already.
quite nice solution in my opinion.
