### ISSUE TITLE
wrong route with urlencoded links

### ISSUE THREAD

**Issue by dhrubajyoti-das** [dannyvankooten/AltoRouter#125]
My site was working properly with altorouter. But when I urlencode any url like this one  ``` <a href="a.html"><img src="https%3A%2F%2Fi.ytimg.com%2Fvi%2Fdz0-OfTQVdk%2Fhqdefault.jpg" /></a> ``` the routing fails. This is a youtube image link but without urlencode the url was working fine
Please, guide how to configure altorouter with urlencoded link. 
Some, sample config will be very helpful.

**Comment by koenpunt** [comment]
I do not see how this is related to AltoRouter? 
Maybe it becomes clear when you post what you have so far

**Comment by dhrubajyoti-das** [comment]
Sorry, for late reply. The issue was not related to AltoRouter. It was a configuration problem with my routes. 
I am a beginner so looking for some through documentation on AltoRouter or detailed sample config configuration to study.

Thanks for your prompt reply.

**Comment by koenpunt** [comment]
Examples are to be found here: http://altorouter.com/

**Comment by dhrubajyoti-das** [comment]
Thanks now my site is working.
