### ISSUE TITLE
Headers to 404 Page Not Found does not work. Blank page.

### ISSUE THREAD

**Issue by XecuteFire** [dannyvankooten/AltoRouter#126]
Anyone could help me understand why the headers that throw HTTP redirect won't work in this code? If my route works, then it shows the page as supposed. But when the route doesn't match (exist), it won't throw the 404 page, only showing a blank page.

Could it be related to WAMP settings (Apache, PHP.ini) or could it be related to the .htaccess file?

Thanks!

```php
/*
 * ------------------------------------------------------
 *  Instantiate the routing class
 * ------------------------------------------------------
 */
 
	$router = new router();

/*
 * ------------------------------------------------------
 *  Map your routes
 * ------------------------------------------------------
 */

	$router->map('GET', '/welcome/', 'WelcomeController#hello', 'welcome_hello');

/*
 * ------------------------------------------------------
 *  Matching the request and processing...
 * ------------------------------------------------------
 */

	$match = $router->match();
	
	if ($match === false)
	{
		header("HTTP/1.0 404 Not Found");
	}
	
	else
	{
		list($controller, $action) = explode('#', $match['target']);
		
		if (is_callable(array($controller, $action)))
		{
			$obj = new $controller();
			call_user_func_array(array($obj, $action), array($match['params']));
		}
		
		else
		{
			header("HTTP/1.0 500 Internal Server Error");
		}
	}
```

```apache
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
```

**Comment by dannyvankooten** [comment]
Sending a "404 Not Found" header is not so much about showing a page but more about telling the browser that the resource is not found. It is up to the server configuration & browser whether they show a custom 404 error page.

A few things to check:

- Is your code running for non-existing routes?
- What do you see when requesting your page from the command line?

`
curl -v http://localhost/some-page
`
- I am not super familiar with WAMP but it could be that you have to explicitly set an `ErrorDocument` in your server config, like this: `ErrorDocument 404 /error.html` 

Hope that helps!
