### ISSUE TITLE
Is it possible to use target PHP files that are outside of the public directory (i.e. above the public/index.php)?

### ISSUE THREAD

**Issue by c5creative** [dannyvankooten/AltoRouter#127]
Greetings,

I hope I've read the documentation carefully. My "front controller (that has the AltoRouter instance & rules) is situated in the root of the Apache-served folder:
```
/home/www/public/index.php
```
My target PHP files are located, however, are located "below" the Apache root, at:
```
/home/www/src/files
# example
/home/www/src/index.php
/home/www/src/blog/index.php
```
I cannot figure out how to get AltoRouter to allow me to use targets that are "upstream" of the index.php.

Appreciate any advice, thanks!
JP

**Comment by bizbink** [comment]
What is your log output?

I can only think of two possibilities; permission error, or not pointing to the correct directory.

**Comment by koenpunt** [comment]
I'm sorry, but this is unrelated to AltoRouter. For help with developing your application or website you better reside to StackOverflow

**Comment by c5creative** [comment]
I did end up figuring it out, thanks. IMO, the documentation what the following does could be improved 
'''
$router->setBasePath
'''
That really was confusing to me for some reason. Perhaps it might be to others. Perhaps I'm too dense.  Anyways, thanks for developing this, I've now got it working nicely within my app.

**Comment by dannyvankooten** [comment]
Awesome. Glad you figured it out! Will look at what we can do to make that more clear in the docs. :-)
