### ISSUE TITLE
Router reacts to GET method when POST route is called without trailing slash

### ISSUE THREAD

**Issue by tzfrs** [dannyvankooten/AltoRouter#128]
I have the two following routes

    $router->map('POST'  , '/pages/[i:id]/posts/[i:postId]/comment/' ,'Comment#add');
    $router->map('GET'  , '/pages/[i:id]/posts/[i:postId]/comment/' ,'Comment#get');

When I'm now calling the first (POST) route without the trailing slash like this:

    /pages/1/posts/1/comment

Instead the get method is called. What can cause this behaviour? Is this a known issue? Is it reproducible? 

This is of course done as a POST-Request, because when I make the same request but with the slash at the end the POST route works without problems.

**Comment by koenpunt** [comment]
The first thing that is being checked when matching routes is the request method; https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L192
So I guess it has something to do with other routes you might have defined?

**Comment by koenpunt** [comment]
Or could it be that your server configuration adds slashes, which make the POST end up as GET

**Comment by dannyvankooten** [comment]
A full list of your defined routes would be really helpful here @tzfrs

**Comment by koenpunt** [comment]
Closing as stale. If your problem still exists please let me know and I'll reopen the issue.
