### ISSUE TITLE
How To Pass 2 Parameters WIthout Having Class

### ISSUE THREAD

**Issue by asisten** [dannyvankooten/AltoRouter#129]
Hello, i have successfully implementing simple one query:
`$router->map('GET|POST', '/login/', 'module/user/login.php', 'login');`
turn into : http://mydomain/login/

but when I have 2 GET parameters it not successfully passed, error said:
Catchable fatal error: Object of class Closure could not be converted 

my map:
`$router->map( 'GET', '/email/[*:getemail]/key/[*:getkey]/', 'module/user/activate.php', 'activate');`

activate.php:
```php
$email = filter_var($_GET["email"], FILTER_SANITIZE_EMAIL);
$key = htmlspecialchars($_GET["key"]);
$getemail = $match['params'][$email];
$getkey = $match['params'][$key];

// and more... code for validation
 ```

my expectation is:
http://mydomain/email/user@email/key/user_key/

Thank you for your help.

**Comment by koenpunt** [comment]
I'm not really sure what you're trying, but `$_GET` params are not involved with AltoRouter.

So what I'm guessing you want to do is the following:

```php
$email = filter_var($match["params"]["getemail"], FILTER_SANITIZE_EMAIL);
$key = htmlspecialchars($match["params"]["getkey"]);

**Comment by asisten** [comment]
Thank you its work !!!  Its look like I have mistaken about getting $_GET var

**Comment by ErikThiart** [comment]
I have a similar issue. 
```
// Dynamic Routes
$router->map('GET','/listing/[*:area]/[*:house]/','listing.php','listing');
```

listing.php
```
<?php
   $area = htmlspecialchars($match["params"]["area"]);          //line7
   $house = htmlspecialchars($match["params"]["house"]);    //line8
?>
<h1>Listing: <?php echo $house; ?></h1>
```

However, I get the following error:
```
Notice: Undefined variable: match in listing.php on line 7
Notice: Undefined variable: match in listing.php on line 8
```

**Comment by dannyvankooten** [comment]
Hi @ErikThiart,

You need to route all requests to `index.php` and then make sure that `listing.php` has access to the `$match` variable. 

Where are you calling `$router->match()`

**Comment by ErikThiart** [comment]
@dannyvankooten sorry for taking so long to respond back I was walking home and grabbed a coffee on my way. 

Alright so, the **.htaccess file** I grabbed from the internet and like any 1337 programmer, assumed it works.
```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.php [L] 
```

Then my **index.php file** is my interpretation of AltoRouter so most probably wrong. 
```
<?php 
//Add the router library
require 'AltoRouter.php';

//Start the router
$router = new AltoRouter();

//Set base path
$router->setBasePath('');

// Static Routes
$router->map('GET','/', 'home.php', 'home');
$router->map('GET','/home/', 'home.php', 'home-home');
$router->map('GET','/about/', 'about.php', 'about');
$router->map('GET','/pricing/', 'pricing.php', 'pricing');

// Dynamic Routes
$router->map('GET','/listing/[*:area]/[*:house]/','listing.php','listing');

// Match the current request
$match = $router->match();
if($match) {
  require $match['target'];
}
else {
  header("HTTP/1.0 404 Not Found");
  require '404.php';
}

?>
```
Document structure:
```
--root
-.htaccess
-index.php
-listing.php
```

Do you require any other information?

**Comment by ErikThiart** [comment]
Bump @dannyvankooten

**Comment by dannyvankooten** [comment]
Hey @ErikThiart,

So what you showed here should actually just work, so after breaking my head over this one for a little while what I _think_ is happening is that you are not actually visiting `test.com/listing/town_name/house_name` but instead you are accidentally accessing `listing.php` directly. Could it be that that is what's going on?

**Comment by ErikThiart** [comment]
Hello @dannyvankooten, nope I thought that as well. 

I am visiting: `test.com/listing/town_name/house_name` 

I tried in opera, firefox, edge, and chrome. On two different PCs.

Just confirm, if you copy the above code and run it on your side, does it work?
If the above code does work on your end, then I will format windows and load ubuntu and send Bill Gates a strongly worded letter.

**Comment by dannyvankooten** [comment]
@ErikThiart 

Hahaha, do that anyway please (the strong worded letter). 

Could you create a [gist](https://gist.github.com/) with all the complete files so that I can take a closer look? It's hard to get a clear picture from what you shared.

Different browsers shouldn't matter, the issue should be in the code that runs on the server's side of things.

**Comment by ErikThiart** [comment]
I will create a zip file with the source code and send that to you.

As for server - running WAMP on windows... :)

**Comment by ErikThiart** [comment]
Hello @dannyvankooten here is the gist with the full code: https://gist.github.com/ErikThiart/99d970afd2e5d9e8f36641ef76393bd1

**Comment by koenpunt** [comment]
I think the problem is that `listing.php` does not have access to the `$match` variable because it's a different file. Making the variable global (`global $match;`) could work, although I would not recommend it.

More info on the matter: https://stackoverflow.com/a/4676007/189431

**Comment by ErikThiart** [comment]
Alright, that makes sense, but if you do not recommend it, how do you implement this functionality then or does Alto not support GET parameters in an URL?

**Comment by ErikThiart** [comment]
I think this must be related to windows.

I copied the code over to an Ubuntu VPS running php and Apache, and it works perfectly, copied it back to WAMP and it does not pass the $match variable. 

VERY strange, do not know how to debug so I will need to look for a different router that's compatible, eish.

Thanks for the help guys.

**Comment by ErikThiart** [comment]
Good lord. I deserve some form of a brownie point. 

I finally managed to get it to work on WAMP/Windows.

I changed the .htaccess file from this:
```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.php [L] 
```
to the following:

```
<IfModule mod_rewrite.c>

   RewriteEngine On

   RewriteCond %{REQUEST_FILENAME}  -f [OR]
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteRule ^(.*)$ index.php [L,QSA]

</IfModule>
```

Can one of you please explain to me what the difference is?
