### ISSUE TITLE
There is some way to ignore a route?

### ISSUE THREAD

**Issue by franklinrabay** [dannyvankooten/AltoRouter#132]
I have the following structure:

. project
.. src
.... controllers
.... models
.... views
...... layouts 
.. public
.... js
.... css

Everytime i try to load a css or js, it matches them routes and redirect to my 404 file...
can i ignore the public path on routes??

**Comment by koenpunt** [comment]
I'm not really sure what you mean, but if you're saying that the routes have precedence over the actual files; that's not really possible.

Could you supply some more information about your (server) setup?

**Comment by franklinrabay** [comment]
my route matching:

if($match && is_callable($match['target'])) {
  call_user_func_array( $match['target'], $match['params']); 
} else  {
  require_once "./404.php";
}

Everytime i try to load a file like css, js, image, etc. the application return the 404 page

i am using nginx

my configs:

http {
        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # nginx-naxsi config
        ##
        # Uncomment it if you installed nginx-naxsi
        ##

        #include /etc/nginx/naxsi_core.rules;

        ##
        # nginx-passenger config
        ##
        # Uncomment it if you installed nginx-passenger
        ##

        #passenger_root /usr;
        #passenger_ruby /usr/bin/ruby;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;

        server {
                   location / {
                        try_files $uri /index.php;
                }
        }
}

**Comment by koenpunt** [comment]
The problem is that you're missing the `root` directive in your nginx config.

Try adding `root /path/to/public;` in the `server {}` block.

**Comment by franklinrabay** [comment]
i think i gave you the general nginx settings... lmao
my project settings are:

server {
    listen  80;

    root /hellofresh/code-test;
    index index.html index.php;

    server_name code-test.hellofresh.dev;

    location / {
        try_files $uri /index.php;
        #try_files $uri $uri/ /index.php?$query_string;
    }

    error_page 404 /404.html;

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        root /usr/share/nginx/www;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

**Comment by franklinrabay** [comment]
But i tried to set root on general settings, but doesn't work... i'm getting crazy with this...

Anyway, thank you a lots for attention

**Comment by koenpunt** [comment]
is this where the index.php resides?

```
. project
.. src
.... controllers
.... models
.... views
...... layouts 
.. public
.... index.php   <=================== 
.... js
.... css
```

**Comment by franklinrabay** [comment]
nops, it resides at root directory

.project
...
.index.php

**Comment by koenpunt** [comment]
What is the url your using to load a css or js file?

**Comment by franklinrabay** [comment]
<script src="./public/jquery-1.11.3/jquery.min.js"></script>

**Comment by koenpunt** [comment]
Try the following common setup;

Place the `index.php` in the public folder and alter include paths etc and update the `root` in the nginx configuration to point to the public folder instead of the project folder.

 Then strip the `/public` part of the js url.

**Comment by franklinrabay** [comment]
There is a beginning, it responds HTTP 500 now

src="public/js/jquery-1.11.3/jquery.min.js"

**Comment by franklinrabay** [comment]
I got it! Resolved, it's only my index.php file... it's out of public path, i put it into and configure my nginx to read from /public path

Thank you very very much ;D
