### ISSUE TITLE
.htaccess issue

### ISSUE THREAD

**Issue by stickypages** [dannyvankooten/AltoRouter#133]
Just curious if this is a problem. I am trying to intregrate an old site, which did use .htaccess for some old url rewrites.

But should the HTACCESS not be rerouting before Alto does? 
IE: here is a sample htaccess.

RewriteEngine On
RewriteRule ^signup(.*)$   landingPages/sign-up.php
RewriteRule ^about(.*)$   landingPages/about.php

-- And now onto Alto
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]

Now I would like to continue to use the htaccess for the older ways. But doesn't seem to work for some reason. 

Any thoughts as to why this might be the case.

**Comment by asisten** [comment]
AFAIK, 
RewriteCond %{REQUEST_FILENAME} !-f  mean if specified file not exist then continue execute rule below.
So in your case, if your request is "signup" or "about", that will checking / treat as file name, if not exist then continue to execute rule below rewritecond.

**Comment by koenpunt** [comment]
What do you want to achieve? You want to keep the old rules working as well?

If I'm correct the following should work:
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^signup(.*)$   landingPages/sign-up.php
RewriteRule ^about(.*)$   landingPages/about.php
RewriteRule . index.php [L]
```

> The [L] flag causes mod_rewrite to stop processing the rule set.
> https://httpd.apache.org/docs/2.2/rewrite/flags.html#flag_l

**Comment by koenpunt** [comment]
Closing as stale. If your problem still exists please let me know and I'll reopen the issue.
