### ISSUE TITLE
Respond to OPTIONS preflight request

### ISSUE THREAD

**Issue by Antman261** [dannyvankooten/AltoRouter#134]
Can we get Altorouter to respond to an OPTIONS request?

I'm sending a cross domain PATCH request via jQuery ajax which sends [preflight](http://www.w3.org/TR/cors/#resource-preflight-requests) OPTIONS check. It would be nice if Altorouter responded to this with 200 OK if there was a path for the requested header.

Example header:
```
OPTIONS /event/87/sets HTTP/1.1
Host: api.localhost.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:42.0) Gecko/20100101 Firefox/42.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://localhost.com
Access-Control-Request-Method: PATCH
Connection: keep-alive
```

Example Suggested Response:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
```

Of course I could just respond to all OPTIONS requests with OK, but that defeats the purpose of checking if the resource supports that action.

**Comment by koenpunt** [comment]
AltoRouter is not in charge of the response, so that's not something we're going to implement.

However, you could extend AltoRouter with something like the following to handle your use case:

You could probably extend AltoRouter with something like this:

```php

class OptionsAltoRouter extends AltoRouter {
  public function match($requestUrl = null, $requestMethod = null){
    $originalRequestMethod = $requestMethod;
    if($requestMethod == 'OPTIONS'){
      $requestMethod = $_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD'];
    }
    if($match = parent::match($requestUrl, $requestMethod)){
      $match['request_method'] = $originalRequestMethod;
    }
    return $match;
  }
}
```

And then check the `request_method` in when matching, and when it's `OPTIONS`, you'll respond with your suggested response. 

```php

$router = new OptionsAltoRouter();
// define routes
$match = $router->match();

if(!$match){
  header('HTTP/1.1 404 Not Found', true, 404);
  exit;
}

if($match['request_method'] == 'OPTIONS'){
  header('HTTP/1.1 200 OK');
  header('Access-Control-Allow-Origin: *');
  exit;
}

```
