### ISSUE TITLE
Problem with a simple example

### ISSUE THREAD

**Issue by bloudman** [dannyvankooten/AltoRouter#137]
Hi!
I've just downloaded AltoRouter on your website .
I began a new project but i've got a problem runing that code:

    include("AltoRouter.php");
    
    $router = new AltoRouter();
    
    $router->map( 'GET', '/', function() {
	    require __DIR__ . '/home.php';
    });
    
    $router->map( 'GET', '/users/[*:id]/', function( $id ) {
        require __DIR__ . '/test.php';
    });

    $match = $router->match();

    var_dump($match);
    if( $match && is_callable( $match['target'] ) ) {
        call_user_func_array( $match['target'], $match['params'] ); 
    
    } else {
    // no route was matched
    echo "404";
    }

It send me a "404" message all the time...

    var_dump("$match")
just return:
    boolean: false

I don't understand why...

**Comment by snopboy** [comment]
Put this right after the $router = new AltoRouter();
```php
$lolwat = 'YOUR REAL BASE PATH HERE, i.e. example.com/clients/myapp is /clients/myapp, if it's just example.com then leave it empty';
$router->setBasePath($lolwat);
```

**Comment by koenpunt** [comment]
Without more context it's hard to say what the problem is. It probably lies in a misconfiguration of the server rewriting. Can you provide some more info about your setup?

**Comment by MLoureiro** [comment]
@snopboy how are you testing it?
have you added the rewrite rules to the `.htaccess`?

**Comment by MLoureiro** [comment]
A simple way to test if is to test with curl, like:

`route.php`
```php
include("AltoRouter.php");
$router = new AltoRouter();
$router->map( 'GET', '/', function() {echo 'Hello World!';});

if(!$router->match()) 
{
    echo 'oops';
}
```

Then curl your server:
```sh
$ curl localhost:8000
Hello World
$ curl localhost:8000/not-matched-path
oops
```

Also if you're using PHP 5.4+, you can use [cli server](http://php.net/manual/en/features.commandline.webserver.php);
```sh
$ cd /path/to/your/app
$ php -S localhost:8000
```

**Comment by snopboy** [comment]
@MLoureiro I assume the OP's issue is that the router always show him error 404 for all routes, not apache.
Thus setting a base path for the router (a native function in the library) to give it the exact base through which it gets the route and parameters, is the solution.

**Comment by MLoureiro** [comment]
@snopboy oops! my bad, I pinged the wrong person, i wanted to ping @bloudman.

The example code he presents is actually the example from the doc's, so I believe he was just starting to try  to make it work, so I think the issue is much simpler.

**Comment by koenpunt** [comment]
@snopboy you make assumptions, which are based on nothing, other than that it helped you once or twice. Without any more details just putting out random solutions isn't going to help anyone.

**Comment by snopboy** [comment]
@koenpunt 
I assume it because the OP clearly stated it.
![Proof m8](https://i.imgur.com/yqSPskM.png)

**Comment by ZsharE** [comment]
Same problem here, is not working on localhost or server, same "oops" message all the time. The paths are good, i tried all the things, but no luck.
Any idea ?

**Comment by dauletico** [comment]
Confirm that @snopboy was right.
I had the same issue, always 404 error, then I set basepath $router->setBasePath('dir/dirrouter'); and it's working now.
Thank you snopboy!
