### ISSUE TITLE
Router does not call func

### ISSUE THREAD

**Issue by snopboy** [dannyvankooten/AltoRouter#138]
Well, it's supposed to parse the target and then the if statement of the is_callable suppose to return true and call it.
It doesn't work.

I setup a simple example.
```php
<?php
basename($_SERVER["PHP_SELF"]) == "router.php" ? die("No direct script access allowed") : '';


$router = new Router();
class controller
{

	function __construct(){}

	function index()
	{
		$lol = 'index';
		echo $lol;
	}
	function update($id = '')
	{
		$lol = 'update ';
		$lol .= $id;
		echo $lol;
	}

}

$controller = new controller();

//if (is_callable(array($controller, 'update'), true, $callable_name)) {echo 'callable';} else {echo 'not callable';}


$router->setBasePath($config['base_url']);

$router->map( 'GET', '/', function() {
	putenv('VIEW=default');
	putenv("PAGETITLE=Home");
}, 'home');


$router->map( 'GET', '/news', function() {
	putenv('VIEW=news');
	putenv("PAGETITLE=News");
}, 'news');

$router->map( 'GET', '/news/test', function() {
	putenv('VIEW=news');
	putenv("PAGETITLE=Test");
}, 'test');

$router->map('POST|GET','/users/[i:id]/update', 'controller@update', 'users_do');

$match = $router->match();
var_dump($match);
logMessage(3, 'Router Loaded');

if ( $match && is_callable( $match['target'] ) )
{
	call_user_func_array( $match['target'], $match['params'] ); 
}
else
{
	// no route was matched
	header( $_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');
	putenv("VIEW=error404");
	putenv("PAGETITLE=Error");
	logMessage(2, 'Route not found');
}
```
The commented line is the one that works (not a part of the routing though), while the mapped one doesn't, I first tried with a hashtag instead of @ but then I saw in the AltoRouter.php match() method that it looks for @ and not #.

When dumping both (# and @) it gives the array as it should BUT, the target is there as target=> 'controller@update' instead of $controller, 'update' which ultimately makes no sense and thus why it is not callable at all and not called.

Any insight?
P.S. I might be wrong, perhaps even dead wrong because I'm still a newbie but I'm trying to learn so if I'm wrong the I apologize and please do tell your reasons, thanks!

Regards,
Snopboy.

**Comment by snopboy** [comment]
@dannyvankooten @koenpunt 
Also it's a great routing system, it will help me a lot in the current project I'm working on, I'm building a micro framework for learning purposes.

**Comment by bellwood** [comment]
@snopboy, not sure if this is the solution but based on my findings after using this for a week or so perhaps this will work:

```php
$router->map('POST|GET','/users/[i:id]/update', function($id) {
$controller->update($id);
}, 'users_do');
```

**Comment by koenpunt** [comment]
You have to parse the `controller@update` action yourself. There is no default controller/action handling in AltoRouter.

So basically, 


```php
$match = $router->match();
if ( $match )
{
    list( $controller_class, $action ) = explode( '@', $match['target'] );
    $controller = new $controller_class();
    call_user_func_array( array($controller, $action), $match['params'] ); 
}
// ...

**Comment by koenpunt** [comment]
@bellwood your example won't work, because the controller variable is not available in the closure.

If you update it like this it could work, (although I don't know if that is what @snopboy wants):

```php
$router->map('POST|GET','/users/[i:id]/update', function($id) use ($controller) {
$controller->update($id);
}, 'users_do');

**Comment by bellwood** [comment]
@koenpunt thanks for the clarification, much appreciated =)

**Comment by snopboy** [comment]
@bellwood 
While using a function instead of an assigned controller could be useful in some cases, it is mostly unused and therefore wont be the best solution, also if you do it your way, you'd have to find a way of defining each route's controller, while striving for simplicity - this is not a good solution. My app is supposed to be foolproof so making it as complicated for newbies as using a function in which you assign the controllers and methods, for each and every route - wont be a really good idea.

@koenpunt 
I wrote a quick dirty script to handle this but it is really a bad one, I'll adjust my script to work with yours, your solution is very good.

Here's the old way of handling it, forgive me for implementing it in such an awful way, I am a beginner and also was doing it for testing purposes.

```php
$match['target'] = explode('@', $match['target']);

if (!empty($match['name']) AND !empty($match['target']) AND $match['name'] != NULL AND $match['target'] != NULL)
{
	include APPPATH.'/controller/'.$match['target'][0].'.controller.php';
	$controller = new Controller();

	if ( $match && is_callable( $controller->$match['target'][1]() ) )
	{
		call_user_func_array( $controller->$match['target'][1]($match['params']) );
		logMessage(3, 'Controller '.$match['target'][0].' and Method '.$match['target'][1].' Loaded');
	}
}
else
{
	include APPPATH.'/controller/errors/404.controller.php';
	$controller = new Controller();

	if ( $match && is_callable( array($controller,'index') ) )
	{
		call_user_func( array($controller,'index') );
		logMessage(2, 'Route not found');
	}
	else
	{
		// no route was matched
		header( $_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');
		putenv("VIEW=error404");
		putenv("PAGETITLE=Error");
		require_once APPPATH.'/view/view.extend.php';
		include(APPPATH.'/view/_templates/layout.sporter.php');
		logMessage(1, 'Error on handling error404 controller');
	}
}
```
