### ISSUE TITLE
Undefined offset: 1  while using AltoRouter

### ISSUE THREAD

**Issue by pivnicki** [dannyvankooten/AltoRouter#140]
Everything was working fine until today. 
Now I'm getting this error Undefined offset: 1  and error is pointed to this line of code 
` list($controller,$method)=explode("@",$match['target']);`

Here is the whole code from index.php :
```
<?php
     include(__DIR__.'/../bootstrap/start.php');
Dotenv::load(__DIR__."/../"); 
include(__DIR__.'/../bootstrap/db.php');
include(__DIR__."/../routes.php");

 $match=$router->match();

 list($controller,$method)=explode("@",$match['target']);

 if(is_callable(array($controller,$method))){
        $object=new $controller();
        call_user_func_array(array($object,$method), array($match['params']));
 }else{
 	 
 	echo "Can not find $controller->$method";
 	exit();
 }
```

**Comment by koenpunt** [comment]
Your target probably doesn't have an `@` in it, how do you define your routes?

**Comment by pivnicki** [comment]
I made it work, well the part of it. Home page is now showing but the login and register page can not be found by the server. I'm using Ubuntu by the way.

As for the routes file, here's the code:

```
<?php

$router->map('GET','/','PageController@getShowHomePage','home');

$router->map('GET','/register','PageController@getShowRegisterPage','register');

$router->map('POST','/register','PageController@postShowRegisterPage','register_post');

$router->map('GET','/login','PageController@getShowLoginPage','login');
```

**Comment by koenpunt** [comment]
OS shouldn't really matter, although server software does. What are you using, nginx or apache?

**Comment by pivnicki** [comment]
I'm using apache both on Windows and on Ubuntu.
The thing is that now everything works fine on Windows but Ubuntu still gives me trouble when I'm trying to load register and login page.

**Comment by snopboy** [comment]
Can you please add the following after the listing?
```php
var_dump($match);
```
Paste here the output so we could have a better understanding of what's wrong with it on your end, because the script works like a charm for me.

If you're struggling to implement it, feel free to rip the implementation I've done here:
https://github.com/snopboy/Sporter

**Comment by pivnicki** [comment]
Here is the var_dump($match);
array(3) { ["target"]=> string(47) "Acme\Controllers\PageController@getShowHomePage" ["params"]=> array(0) { } ["name"]=> string(4) "home" } 

I feel the need to say once again, if you don't mind, on windows it works fine as it should but on Ubuntu only home page is showing but the other pages are blank, just white with nothing on them even tho I have echoed some descriptive strings on them so I can tell them apart.

**Comment by koenpunt** [comment]
Do you have error reporting enabled?

```php
error_reporting(E_ALL);
ini_set('display_errors', 'on')

**Comment by snopboy** [comment]
I'm a complete noob but, are you using namespaces or is the the actual path? if it's the actual path, try replacing the \ with /
Also, it should give you errors if your error reporting is enabled.

**Comment by pivnicki** [comment]
@koenpunt 
Yes I have enabled error reporting.

@snopboy 
Yes those are the namespaces. The Acme is the name I have set up in composer.json file
~~~
{
    "autoload": {
        "psr-4": {"Acme\\": "src/"}
    }
}
~~~
Today instead of the blank page I get this when I'm trying to load register page and I have the register page in the views
~~~
Not Found

The requested URL /register was not found on this server.
~~~

Here is the .htaccess file

~~~
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
~~~

**Comment by YannickFricke** [comment]
Which version of php are you running on windows and on ubuntu?

**Comment by snopboy** [comment]
In that case I apologize for not being able to help you. I'm a beginner developer and my knowledge of namespaces and the advanced PHP 5 stuff is very little, same goes for composer, haven't used any of this yet.

**Comment by pivnicki** [comment]
@YannickFricke  

Windows

~~~
PHP 5.5.30 (cli) (built: Sep 30 2015 13:50:53)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
~~~

Ubuntu

~~~
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:32:13)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
~~~

@snopboy 

That's ok, I appreciate your input and good will.

**Comment by YannickFricke** [comment]
@pivnicki are you using the latest version of AltoRouter?

**Comment by pivnicki** [comment]
@YannickFricke 
Yes 
~~~
"altorouter/altorouter": "1.1.0",
~~~

**Comment by snopboy** [comment]
Although not being experienced enough to provide support, I think adding the following after the listing will give us more idea of what's going on. The var_dump info output you provided shows the '@' which is not supposed to, it supposed to break everything before the '@' to [0], and the latter to [1] in an array.
```php
var_dump($match, $controller, $method);
```
It should be after the following line
```php
list($controller,$method)=explode("@",$match['target']);
```

**Comment by koenpunt** [comment]
What is the error you're seeing? Is it an Apache error, or your own "Can not find ..." message?

**Comment by pivnicki** [comment]
It's 404 page not found error by Apache .

**Comment by koenpunt** [comment]
Then the issue is not with AltoRouter but with your server configuration.

**Comment by koenpunt** [comment]
Although the rewrite rule above looks correct to me

**Comment by snopboy** [comment]
Try setting a base path maybe? You should set it both in the htaccess (RewriteBase) and in the router ($router->setBasePath()), if that doesn't work then it's probably a misconfiguration of your Apache engine.

**Comment by koenpunt** [comment]
@snopboy I appreciate the effort, but just suggesting random tryouts is not going to work.

It's obviously something with his Apache configuration. Are rewrite rules from a `.htaccess` allowed?

**Comment by snopboy** [comment]
@koenpunt Actually, I meant for RewriteBase which is supposed to be in the htaccess file (this tells the apache engine what is the base virtual directory to use when messing with urls there, so technically even if you redirect all requests that aren't files/folders to index.php, it could still fail in doing so if the RewriteBase is not set correctly), and it seems like a very likely cause for this issue.
When you come to think of it, it's possible that the rewrite module is not loaded as well.

**Comment by koenpunt** [comment]
I know apache. But when `RewriteBase` is not set, the location of the `.htaccess` is assumed to be the base. So adding `RewriteBase` and a base path in the router is just making it over-complicated. 

> it's possible that the rewrite module is not loaded as well. 

That's sound sensible.

**Comment by YannickFricke** [comment]
@koenpunt I'm setting booth and never expected any problems. Testing locally with apache and server is nginx.

@pivnicki Can you upload your php info to pastebin?

**Comment by koenpunt** [comment]
I don't say it is causing problems, but why make @pivnicki's setup more complicated?

**Comment by pivnicki** [comment]
I have finally solved the problem.
I have made virtual host and added the next code:

` <Directory /var/www/html/phpapp/public>
      <IfModule mod_rewrite.c>
      Options -MultiViews
      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} !-f
     RewriteRule ^ index.php [L]
   </IfModule>
</Directory>`
