### ISSUE TITLE
Negatives are not being considered as a valid integer field

### ISSUE THREAD

**Issue by Alvaroctal** [dannyvankooten/AltoRouter#142]
Maybe is pretty obvious and easy to solve, but, in my code:

`array( 'GET', '/api/near/[i:coordx]/[i:coordz]/[i:index]/', 'proyectos/near')`

if one of the coords becomes negative the api doesn't consider that request as a match due to this line:
`protected $matchTypes = array('i'  => '[0-9]++', [...]`
must be:
`protected $matchTypes = array('i'  => '-?[0-9]++', [...]`

**Comment by koenpunt** [comment]
IMO it's not common to have negative integers in a url, but if you want to support them you can simply update the `$matchTypes` using `addMatchTypes`:

```php
$router->addMatchTypes(['i' => '-?[0-9]++']);
```
