### ISSUE TITLE
[REQ] Enumerating available routes?

### ISSUE THREAD

**Issue by bellwood** [dannyvankooten/AltoRouter#143]
I'm looking to extend the functionality of Alto and wanted to know if there was a way to enumerate all defined routes?

Among the reasons:
-dynamic sitemap
-navigation
-intelligent 404

Intelligent 404 would be done via ingesting the request, using metaphone() or soundex() to find similar routes and make them visible (e.g "Did you mean...")

Thank you for your input =)

**Comment by koenpunt** [comment]
I've extended AltoRouter with one of the functions being the visualization of the routes. (Just like Rails does)

Here's a snippet;

```php
                $columns = call_user_func_array('array_map',array_merge(array(null), $this->routes));
		$names = array_pop($columns);
		list($methods, $routes, $targets) = $columns;
		
		$column_sizes = array();
		foreach($columns as $_column){
			$column_sizes[] = max(array_map('strlen', $_column));
		}
		
		$name_size = max(array_map('strlen', $names));
		
		$rows = count($this->routes);
		for($i = 0; $i < $rows; $i++){
			$line = str_pad($names[$i], $name_size + 3, ' ', STR_PAD_LEFT) . ' ';
			foreach($columns as $_column_index => $_column){
				$line .= str_pad($_column[$i], $column_sizes[$_column_index] + 1, ' ', STR_PAD_RIGHT);
			}
			$lines[] = $line;
		}
		
		echo implode("\n", $lines) . "\n";

**Comment by bellwood** [comment]
@koenpunt thanks, I gave it a go and didn't get very far- between adding it as a public function in the class and using it in my project after Alto has been defined but no dice (presumably user error)

However, whilst in Alto I noticed:

```
	/**
	 * Retrieves all routes.
	 * Useful if you want to process or display routes.
	 * @return array All routes.
	 */
	public function getRoutes() {
		return $this->routes;
	}
```

So i threw that in a route with a call back:

```
$router->map('GET','/sitemap/', function($routes = $router->getRoutes()) {
    print_r( $routes );
},'sitemap');
```

but that renders a parse error - so I tried:
```
$routes = $router->getRoutes();
print_r( $routes );
//$router->map('GET','/sitemap/', function($routes = $router->getRoutes()) {
//    print_r( $routes );
//},'sitemap');
```

and hey I see all my routes but it's not useful there - so I did:

```
$routes = $router->getRoutes();
$router->map('GET','/sitemap/', function($routes) {
   echo '<h3>Your routes</h3>'; 
   print_r( $routes );
},'sitemap');
```

... and now /sitemap/ loads but I get no routes displayed, just my heading...

This feels like day 1 stuff here but I cannot get it to allow me to dump all routes within a callback

Thanks for the feedback - much appreciated =)

**Comment by Antman261** [comment]
Simple fix - you're sending a function to a later callback, it can't access ````$routes```` because you defined it outside the function. The param in the function passed as a parameter to map is derived from the match, not from the context of the function definition in the map arguments.

````
$router->map('GET','/sitemap/', function() {
   $routes = $router->getRoutes();
   echo '<h3>Your routes</h3>'; 
   print_r( $routes );
},'sitemap');
````

**Comment by koenpunt** [comment]
Oh that's right, `getRoutes` was implemented later. 
@Antman261's solution should work when you make the `$router` available to the callback like so:

```php
...function() use ($router) {
```

**Comment by bellwood** [comment]
@koenpunt @Antman261 Thank you both very much, this worked beautifully - appreciate your assistance =)

**Comment by bellwood** [comment]
Just a quick revisit to this - getting a warning using this:

```
Warning: Missing argument 1 for {closure}() in /index.php on line 13
```

```
// SITEMAP
$router->map('GET','/sitemap/', function($routes) use($router) {    <-- LINE 13
    echo '<h3>Defined routes</h3>';
    $routes = $router->getRoutes();
    echo '<pre>';
    print_r( $routes );
    echo '</pre>';
},'sitemap');
```

**Comment by koenpunt** [comment]
```php
$router->map('GET','/sitemap/', function($routes) use($router) {
```
Should be 
```php
$router->map('GET','/sitemap/', function() use($router) {
```

**Comment by bellwood** [comment]
Well that was quick!

Thank you =)
