### ISSUE TITLE
[REQ] Routes as an array OR string

### ISSUE THREAD

**Issue by bellwood** [dannyvankooten/AltoRouter#145]
Would it be possible to permit the route path to be an array of paths OR a string?

In many cases I have several routes that would all render the same view and in the spirit of DRY it would be awesome if we could pass an array of routes.

Thank you for your consideration =)

**Comment by bellwood** [comment]
Feel like some context will help here, I'm trying to avoid:

```php
$router->map('GET','/productname/', 'views/productname'},'productname');
$router->map('GET','/product-name/', 'views/productname'},'productname');
$router->map('GET','/old_url_naming_convention_product_name/', 'views/productname'},'productname');
$router->map('GET','/product-name-for-that-one-time-the-ceo-actually-wanted-this/', 'views/productname'},'productname');
```

What I'd like:

```php
$productname = ['productname','product-name','old_url_naming_convention_product_name','product-name-for-that-one-time-the-ceo-actually-wanted-this'];
$router->map('GET',$productname, 'views/productname'},'productname');
```
I'm in a project that has come through several structural/url changes and they have them all mapped with redirects within PHP using a poor-mans router

It would be nice to simply pass an array of routes if you had many routes all doing the same thing.

Thanks =)

**Comment by bellwood** [comment]
...and actually the above "what I'm trying to avoid" doesn't even work as you can't redeclare routes, soooo....

**Comment by koenpunt** [comment]
You can define a route with a regular expression, which will give you lots of flexibility.

For example to match `product-name` and `productname`, you could use the following;

```php
$router->map('GET', '@^/product-?name/', ...)

**Comment by bellwood** [comment]
@koenpunt I'll give that a go... One off cases can always be handled in the .htaccess as needed... Thanks =)
