### ISSUE TITLE
trying to  make a simple example work

### ISSUE THREAD

**Issue by ambicoder** [dannyvankooten/AltoRouter#148]
I have a script named blog_show.php and it's full path is `http://localhost/Appointments/Frontend/blog_show.php`

In it I have placed the following code:
```
$router = new AltoRouter();
 $router->map( 'GET', 'http://localhost/Appointments/Frontend/blog_show.php', function() {
    require __DIR__ . '/views/home.php';
});
```
IF i have understand correctly when the browser points to the above address a redirection should take place to /views/home.php. This does not happen in my case.I do not have home.php anywhere in my folder structure(a **no found** warning should have been issued)...it is just for testing.

Either the code above is wrong either it is not intended for what I think.Please explain a little bit....

Thanks

**Comment by koenpunt** [comment]
What you have is not correct, did you take a look at http://AltoRouter.com ?

**Comment by ambicoder** [comment]
I read the docs....I have understand better how routing works....nonetheless I cannot make it work,let me explain.
In blog_show.php I have this code:

`$router->map( 'GET', '/', function() {
    require __DIR__ . '/views/home.php';
});`

I also have this link in it(in the same script):
 `<a href="http://localhost/Appointments/Frontend/blog_show.php">test allrouter</a>`

Now....from what I have understand clicking the link will trigger a redirection to views/home.php,something which does not happen in my case.

P.S I do not have home.php anywhere in my folders,,,,show I should get a Not found message.Since it is for testing purposes I am not using a real file...it does not matter in this case.

**Comment by koenpunt** [comment]
I'm very sorry, but if you followed the steps on the website, you should be doing things differently. Especially the part where it states that the router should be constructed in a `index.php` and having your server configured to pass all requests to it.

And in all cases, AltoRouter doesn't redirect anything, so if you're looking for redirects in any way, you will save to implement that yourself.

Anyways, GitHub issues are used for problems with implementation and actual bugs, but this is more leaning to support on programming with php in general. For further support you could reside to stackoverflow.com
