### ISSUE TITLE
Does it have the "Route namespaces" feature of klein?

### ISSUE THREAD

**Issue by thinsoldier** [dannyvankooten/AltoRouter#149]
https://github.com/klein/klein.php#route-namespaces

**Comment by koenpunt** [comment]
Nope, it doesn't. If you can update your issue to make it a feature request; that would be great

**Comment by thinsoldier** [comment]
@koenpunt I will do a rough implementations both with and without using that feature to see if I really need it.

What exactly makes AltoRouter different/better than klein?

**Comment by koenpunt** [comment]
AltoRouter is focused on matching urls; the action of a route can be anything, and handling of it is left entirely to the user, whereas Klein has a large set of classes and methods for handling requests and responses.
