### ISSUE TITLE
Found weird issue/bug

### ISSUE THREAD

**Issue by AlexioVay** [dannyvankooten/AltoRouter#151]
I think I found a weird issue or bug. When you name a route like the filename like this:

`

> $router->map('GET','/account/', 'account.php', 'account');

`

it works fine locally but not on the remote host. So I had to rename account.php to singup.php in this case to get it work on the remote. Does someone know why?

**Comment by YannickFricke** [comment]
What does your PHP-Log say?

**Comment by AlexioVay** [comment]
This is individual. For example there are some functions in the signup.php that I'm loading and I'll get the "undefined function" error. Also all HTML/CSS aren't loaded like the other mapped routes. But this only happens on the remote server, not locally. After I renamed it, it worked fine however.

**Comment by YannickFricke** [comment]
Then rename it back and check your logs. There should be an error.

**Comment by koenpunt** [comment]
How do you handle matches?

**Comment by koenpunt** [comment]
@AlexioVay it has been more than a week, and it is not clear to me what is going wrong. Also because there's no reason why the filename should conflict with a routename, as they have no dependency on each other. If you think this issue hasn't been resolved, please let me know.
