### ISSUE TITLE
How to use a middleware method and pass the results on ?

### ISSUE THREAD

**Issue by EduardJS** [dannyvankooten/AltoRouter#152]
Hello guys, I remember I read something on the website, I just can't find it anymore, or I just think I read it at some point in time. 

Is there any way to use like... nodejs's Express, `app.use` middleware, to validate the `authentication headers` etc, then just pass it on so we can use it in the callback ? Or is that up to us ?

**Comment by koenpunt** [comment]
That's up to your implementation, AltoRouter focusses on routing.
