### ISSUE TITLE
Generate URL with regex

### ISSUE THREAD

**Issue by cynephoba** [dannyvankooten/AltoRouter#153]
Hi,

Having troubles using the $router->generate() method.
This is my URL that i've defined:

`$router->map('GET', '@^\/([Bb]rowse\/?(?<levelslug>[0-9A-Za-z_-]*?)?\/?(?<postslug>[0-9A-Za-z_-]*?)?\/?)$', 'browseView', 'Browse');`

Then i'm calling the method `$router->generate("Browse", ["levelslug" => "slug-url-level", "postslug" => "slug-url-post"]);`.

Given my basepath is `/site`, I would expect it to build the url `/site/slug-url-level/slug-url-post`. 
However this is the url I am getting returned:
`/site@^\/([Bb]rowse\/?(?<levelslug>[0-9A-Za-z_-]*?)?\/?(?<postslug>[0-9A-Za-z_-]*?)?\/?)$`

I believe my regex is correct as visiting the site on that URL works without any issues whatsoever (allows me to visit **/site/browse**, **/site/browse/level** or **/site/browse/level/post** (with optional trailing slashes and optional uppercase initial letter). 

Any help would be appreciated.

**Comment by YannickFricke** [comment]
Register your regex strings in alto router and then use them.

I think plain regex is not suported by the generate()-method.

So you only have to register your regex in Alto Router.

**Comment by koenpunt** [comment]
Reverse routing for custom regexes is not supported. Like @YannickFricke, register your regex'es with `addMatchTypes`, and then use those in a regular route. More on that here: http://altorouter.com/usage/mapping-routes.html

**Comment by koenpunt** [comment]
Something like this could work:

```php
$router->addMatchTypes([
  'slug' => '[0-9A-Za-z_-]*?'
]);

$router->map('GET', '/browse/[slug:levelslug]?/[slug:postslug]?', 'browseView', 'Browse');
