### ISSUE TITLE
No returns from controllers.

### ISSUE THREAD

**Issue by val4o0o0** [dannyvankooten/AltoRouter#158]
I have this:
`$router->map('GET','/users/[i:id]/', 'Controllers\User#displayUser');`

My class is this:

```
<?php
  
namespace Controllers;

class User {
  
  public function displayUser($id) {
    $myfile = fopen("testfile.txt", "w");
   return $id;
    
  }
  
};
```

But nothing happens ? 
htaccess is ready, and routing is working. 
```
// match current request
$match = $router->match();
var_dump($match);
```
gives me:

```
array (size=3)
  'target' => string 'Controllers\User#displayUser' (length=28)
  'params' => 
    array (size=1)
      'id' => string '5' (length=1)
  'name' => null
```

I expect to route gives me back $id value or creating the file testfile.txt, but nothing happens...
I Use Aura Autoloader and my classes working perfect with this autoloader. In AltoRouter maybe is not working ? I don't know, please help me.

**Comment by koenpunt** [comment]
AltoRouter doesn't invoke anything, you'll have to use `match`, and handle the result yourself. 

In your case that will mean you'll have to split target on `#`, construct the controller of the first part, and call the second part as method of the controller.

**Comment by VentyCZ** [comment]
I think there should be a complete example on the homepage & in README.md tho, because I think most  of the newcomers won't get it (as he & I) didn't, until they read the docs on the webpage. I mean that you should use the example from processing-requests page as the bare-bone example.
