### ISSUE TITLE
The ending slash problem

### ISSUE THREAD

**Issue by VentyCZ** [dannyvankooten/AltoRouter#159]
I just started using this class and I quickly noticed that I had to modify it a bit, ex. /controller/ wan't mapping to /controller, because the class does not handle request & route path does not need to have the ending slash. So I changed it, so **all the paths always start with slash, but never end with one**.

Like this:
`$route = '/' . trim($route, '/');` - map function
`$this->basePath = '/' . trim($basePath, '/');` - setBasePath function
`$requestUrl = '/' . trim($requestUrl, '/');` - match function, just before foreach call

It works flawlessly on my end, so you should consider changing the behavior.

**Comment by dannyvankooten** [comment]
Hi @VentyCZ ,

We're basically following NGINX specifications here and leaving this up to the user. If you want to have trailing slashes, you can add them to your routes. If you don't want 'em, then you omit them. 

This is most likely best solved by either always redirecting to the preferred URL version from your server config or using the following `try_files` directive.

```
try_files $uri $uri/ =404;
```
