### ISSUE TITLE
Map route to redirect twig templae

### ISSUE THREAD

**Issue by hermanoloco** [dannyvankooten/AltoRouter#160]
Hi, is it possible to use a single file, for example: redirect.php, to map routes with a parameter or with closere method or with a controller,that depends of passed value?

**Code index.php**
Option 1:
$router->map( 'GET', '/', function() { require **DIR** . '/redirect.php'; }, 'go_to_view1');
$router->map( 'GET', '/users', function() { require **DIR** . '/redirect.php'; }, 'go_to_view2');

or Option 2:
$router->map( 'GET', '/', 'redirect.php', 'go_to_view1' );
$router->map( 'GET', '/users', 'redirect.php', 'go_to_view2');

**Code redirect.php**

```
$loader = new Twig_Loader_Filesystem(array('views', 'includes', 'includes/languages/en', 'includes/languages/es', 'includes/languages/it', 'includes/languages/zh'));

$twig = new Twig_Environment($loader);

if($pass_parameter == 'go_to_view1'){
    echo $twig->render('view1.php', array('textos'=>$textos['idioma']));   
}elseif($match['name'] == 'historia'){
    echo $twig->render('view2.php', array('textos'=>$textos['idioma'], 'historia'=>$historia['idioma']));
}
```

Thanks

**Comment by koenpunt** [comment]
Yes both are possible, because it should be your implementation that handles the matched route. Have you followed the steps on altorouter.com ?

**Comment by hermanoloco** [comment]
Yes, I've followed the steps but I don't do it well using Twig Template. I don't know it what I am doing bad. Thanks koenpunt

**Comment by hermanoloco** [comment]
I've solved the problem, in index.php

    $loader = new Twig_Loader_Filesystem(array('views', 'includes', 'includes/languages/en', 'includes/languages/es', 'includes/languages/it', 'includes/languages/zh'));

    $twig = new Twig_Environment($loader);

    $router->map( 'GET', '/', function() { require DIR . '/redirect.php'; }, 'go_to_view1');
    $router->map( 'GET', '/users', function() { require DIR . '/redirect.php'; }, 'go_to_view2');

    $match = $router->match();
 
    if($match && is_callable($match['target'])) {       
        switch ($match['name']) {
            case 'go_to_view1':
                echo $twig->render('view1.php', array('textos'=>$textos['idioma']));
                break;
            case 'go_to_view2':
                echo $twig->render('view2.php', array('textos'=>$textos['idioma'], 'historia'=>$historia['idioma']));
                break;
            default:
                echo $twig->render('inicio.php', array('textos'=>$textos['idioma']));
                break;
        }        
    }else{
        header( $_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');
    }

Thanks @koenpunt

**Comment by 19h47** [comment]
Hi, I know it's old but I was in the same issue, and I wanted to share with you how I instanciate __Twig__ and __AltoRouter__.  
What I do is pass `$twig` to the `call_user_func_array`function.

```
call_user_func_array( $match['target'], $match['params'], $twig ); 
```
Then you can call `$twig` in your ìndex.php`

Hope it helps

**Comment by benzon** [comment]
Or go the even simpler route

`$router->map( 'GET', '/', function() use ($twig) { require DIR . '/go_to_view1.php'; }, 'go_to_view1.php');`
