### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by Luisjavier2008** [dannyvankooten/AltoRouter#161]
```
listing/search/[:name]
listing/search/person-names/[:name]

```
For some reason when I access to  listing/search/person-names/[:name] it matches the listing/search/[:name] route, any clue of what can be the problem here?

sorry i dint found a place to left this kind of questions.

**Comment by koenpunt** [comment]
Reversing the definition order should fix it. Although the routes are defined as not-greedy, so order shouldn't actually matter.

**Comment by Luisjavier2008** [comment]
yes changing the order actually fixed thanks
