### ISSUE TITLE
String with spaces = %20

### ISSUE THREAD

**Issue by tdias25** [dannyvankooten/AltoRouter#162]
i have the following rule to get a search term: 

`$router -> map('GET', 'search/[:query]', 'search#index', 'search');`

but the spaces between the words are coming with %20.

how can i fix this?

sorry for bad english.

**Comment by YannickFricke** [comment]
[*:query]

**Comment by tdias25** [comment]
same

**Comment by koenpunt** [comment]
That's just how an URL works, the spaces are replaced by the browser. You can simply do a string replace in your implementation for `%20`, or use a query param instead (recommended).

**Comment by tdias25** [comment]
what you mean with a query param?

**Comment by koenpunt** [comment]
`/search?q=my+search+query` and to get the value you use `$_GET['q']`
