### ISSUE TITLE
Calling modals on every webpage?

### ISSUE THREAD

**Issue by AlexioVay** [dannyvankooten/AltoRouter#167]
I'm using Altorouter (http://altorouter.com/) for routing on my webpage. 

For example this is how I call my home webpage:

    $router->map('GET', '/', 'home.php', 'home');

So the second parameter checks for the current URI. Now I want to open a modal, for example with `#login-modal` at the end of the URI but I don't know how to implement this that this will be executed on every webpage, no matter if I'm in `/user/`, `/about/` or somewhere else.

So e.g. `/user/#login-modal` and `/about/#login-modal` should call the same login modal, because the login button is clickable on every webpage.

How can I achieve that? Or ist it really necessary to define all webpages for all modals?

**Comment by koenpunt** [comment]
Hashes in URLs can not be handled by AltoRouter, because the hash is only client side. You should use JavaScript to make some modal appear for `#login-modal`.
