### ISSUE TITLE
Missing argument 1 for {closure}(), called in /home/shashwat/Documents/Neutron/system/app.php on line 17 and defined

### ISSUE THREAD

**Issue by Shashwat-AI** [dannyvankooten/AltoRouter#169]
I'm trying to implement MVC in my app
but the code seems to giving a warning
<?php`
$app->route('GET|POST','/[i:controller]/[i:action]',function($controller,$action){
      global $app;
      $app->render($controller,$action);
});`
?>
the original function
`class app{
public function route($method,$url,$function){
          // map url
         $router = new AltoRouter();
         $router->map( $method, $url, $function());
       }`

**Comment by dannyvankooten** [comment]
HI @Shashwat-AI ,

This error is coming from the `system/app.php` file, not from the AltoRouter code itself. So I'm sorry but we can't really help you with that.
