### ISSUE TITLE
.htaccess issue? 505 Internal Server Error

### ISSUE THREAD

**Issue by AlexioVay** [dannyvankooten/AltoRouter#172]
I have a `.htaccess`-file with this code:

    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule . index.php [L]

  [1]: http://altorouter.com/

I developed my website for some months now and I'm ready to publish it, so I never had problems on my localhost. 

But uploading the same `.htaccess`-file is causing troubles on my remote host.

**I noticed this behaviour:**

 - If I'm at my root directory, e.g. `www.domainA.com`, everything works fine
 - As soon as I click on a link on my website like `www.domainA.com/signup/` the loading indicator in my browser spins forever (like **30minutes**!)
 - The same index page is displayed all the time, nothing new loads

So for this long time I can't do *anything*, even if I delete the `.htaccess`-file from the remote server and refresh the page. I have to wait like 30minutes until the page responds again with a 

> 505 Internal Error

page.

**If my problem is about AltoRouter**, I can only assume it is the option setting the base path:

    $router->setBasePath('/projectA');

But since my folder names are the same both on localhost and on my remote web root, I don't know if the problem is there.

__

Sidenote: My web root is organized like the following structure. I seperated each folder by domain.

`[domainA]`

`[domainB]`

`[domainC]`

So it's similiar to my local structure. If I call `localhost/domainA` in my browser it's `C:\xampp\htdocs\domainA`.

PS: My provider just told me that there are no log files I can check. I have to check htaccess errors for myself.

Question also on SO: http://stackoverflow.com/questions/40738375/altorouter-htaccess-file-leads-to-500-internal-server-error

**Comment by YannickFricke** [comment]
Try

`$router->setBasePath('/');`

**Comment by AlexioVay** [comment]
Thanks, I found the solution. Just removing the whole setBasePath line since I'm in the root folder on my webhost.
