### ISSUE TITLE
Problem with some characters

### ISSUE THREAD

**Issue by tdias25** [dannyvankooten/AltoRouter#173]
i'm using a router with this config:

`$router -> map('GET', 'search/[:query]', 'search#index', 'search');`
(i also have tried with [*:query])
but if a hit some search with char like: **í, ã ê** ...and so on, it doesnt work, how can i fix it?

sorry for bad english.

**Comment by dark-cms** [comment]
Please test it with "Catch all"

`$router` -> map('GET', 'search/[*:query]', 'search#index', 'search');

But please provide a sample uri

**Comment by flodi** [comment]
I have the same problems with characters like "," or "_" or "-".

I tried with [:value] and [*:value] with the same results.

For example the URL
http://web.g2eventi.com/eventi/ospiti/associa/2185,2186/
or
http://web.g2eventi.com/eventi/ospiti/associa/2185_2186/
or
http://web.g2eventi.com/eventi/ospiti/associa/2185-2186/

is not catched by
$fw->map( 'GET|POST', '/eventi/ospiti/[a:action]/[a:type]/[*:value]/', 'eventi#ospiti');
or
$fw->map( 'GET|POST', '/eventi/ospiti/[a:action]/[a:type]/[:value]/', 'eventi#ospiti');

**Comment by flodi** [comment]
I even tried defining a type for myself

$this->app["router"]->addMatchTypes(array('l' => '(.+,)*.+'));

It seems the problem is before the matching is tried.

**Comment by flodi** [comment]
Ok, found the problem. My head. :-( Sorry for having bothered you for nothing.

**Comment by mastacontrola** [comment]
@flodi can you describe what you were doing wrong so somebody else who stumbles across has an answer?

Of note it seems like maybe missing the trailing / possibly?

**Comment by koenpunt** [comment]
@mastacontrola His example urls have less path segments than his route, so that doesn't match.

**Comment by koenpunt** [comment]
A greedy route parameter would look like `[**:query]`, so something like this might work;

```php
$router->map('GET', 'search/[**:query]', 'search#index', 'search');
```

Closing since apart from this comment, the issue became stale.
