### ISSUE TITLE
Transformations of dynamic properties

### ISSUE THREAD

**Issue by mattsah** [dannyvankooten/AltoRouter#174]
Hello,

I'm looking at AltoRouter as possible alternative to FastRoute because it offers reverse routing, but one of the concerns I have is ability (or lackthereof) to transform dynamic attributes.  For example, let's say I define matchtype of `c` to match a dynamic element that should be a php class, like a controller class, such that:

`/[c:controller]/[i:id]` could map to `[controller]Controller::select`

When I handle the matched route, I would then aim to replace the value of the controller parameter in the target before parsing, instantiating the controller, etc.  This allows for dynamic targets as well as URLs.  The problem comes if there are multiple words involved.  In the URL they should probably be dash separated, in the target they would need to transform into snake case, e.g.:

`/user-roles/1` should go to `UserRolesController::select`

Obviously I would want this in reverse too.  From what I can tell AltoRouter doesn't support this, but I'm wondering if I did a pull request to add transformers if it would be accepted.  The idea would be something like:

`$router->addTransformer('c', new ClassNameTransformer())`

Transformers would have an interface two methods, one for inbound and one for outbound transformations.

```php
class ClassNameTransformer
{
    public function fromUrl()
    {
         // transform inbound dynamic attribute
    }

    public function toUrl()
    {
        // transform outbound dynamic attribute
    }
}
```

If this is a feature you think might be of some value, I could work on a pull request. Obviously the replacement of the paremeter in the target would still be up to the user, just as all target resolution is, so as far as AltoRouter is concerned the params array in the match would just contain the transformed value.

**Comment by dark-cms** [comment]
why not use the given methods 

`// map users details page
$router->map( 'GET|POST', '/[a:controller]/[i:id]/', function($controller, $id ) {
if (class_exists($controller.'Controller')) {
            call_user_func_array([array$controller.'Controller', 'select']), [$id]);
        }
});`

**Comment by mattsah** [comment]
@dark-cms you mean aside from the fact that it doesn't handle reverse routing simultaneously?  Also, while that may work for a controller where the parameter name is always the same, it may not work for other parameters which transforms are desired, e.g. Dates, IDs to entities/models, or even just a basic multi-word segment.

**Comment by koenpunt** [comment]
I think that reverse routing using so called transformers is going to add a lot of complexity to the codebase. But maybe you can show some (pseudo)code on how you intend to handle this?

**Comment by mattsah** [comment]
I'm asking to add simple parameter transformation callbacks.

Currently, users can add their own match type in addition to the built in match types.  The match type is generally a single character that maps to a regular expression.

All I intend to do is add the ability to add transformers for match types, such that the parameters one receives back have been run through the match callback based on their type.

With the exception of the interface, this would probably only add 2 or 3 lines.  The `generate()` method already parses the parameter type for replacement

```php
foreach($matches as $match) {
	list($block, $pre, $type, $param, $optional) = $match;

	... 
}
```

All I would be adding is something like:

```php
if (isset($this->transformers[$type])) {
	$param = $this->transformers[$type]->toUrl($param);
}
```

Similarly, when routes are compiled, the type is parsed.  So the compiled route would probably get converted to an array containing the regex and the param types.

Then in the existing code where it currently does:

```php
foreach($params as $key => $value) {
	if(is_numeric($key)) unset($params[$key]);
}
```

It would also be added:

```php
$type = $route['paramTypes'][$param];

if (isset($this->transformers[$type])) {
	$params[$key] = $this->transformers{$type]->fromUrl($value);
}
```

I mean, I'm going to have to fork this anyway so I can move along with my project.  I'm under deadlines and I've already switched the router 3 times trying to find something that is nicely suited.  That said, I'll just do a pull request and you can either accept or reject.

**Comment by koenpunt** [comment]
> I'll just do a pull request and you can either accept or reject.

👍

**Comment by mattsah** [comment]
Pull request #178

**Comment by mattsah** [comment]
This is no longer needed as there's a fork which has better ongoing maintenance and community enhancements.  Thanks.
