### ISSUE TITLE
Route length issues ?

### ISSUE THREAD

**Issue by jarodium** [dannyvankooten/AltoRouter#175]
Hello there

I have the following declarations:

```php
$router->map('POST','/[*:chave]/actualizar_compra',array('c' => 'clientes', 'a' => 'actualizar_compra'), 'actualizar_compra');
$router->map('POST','/[*:chave]/registar_compra',array('c' => 'clientes', 'a' => 'registar_compra'), 'registar_compra');
```
The route declared on 'registar_compra' is matched, but the 'actualizar_compra' does not match. 
The full request is to http://m-domaincom.thcloud.com/6c7f307893c9f5b3299bd79b196033345a1f9379/actualizar_compra

I was wondering if the '6c7f307893c9f5b3299bd79b196033345a1f9379' could be too long for altorouter to handle.

Best regards

**Comment by koenpunt** [comment]
Try without the `*` in your route, to make it non-greedy.

Also, AltoRouter doesn't have limits on the length of the url or segments thereof, so "too long" can't be the issue here.

**Comment by koenpunt** [comment]
You can see the different match-types here: https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L23-L30

**Comment by jarodium** [comment]
Will check. 

Thanks.
