### ISSUE TITLE
Uploading a file

### ISSUE THREAD

**Issue by WingRS** [dannyvankooten/AltoRouter#177]
Hi, it's me again. Trying to upload a file with a form like this:
````
<form action='/admin/' method='post' enctype='multipart/form-data'>
	<input type='file' name='file' id='file'/>
	<input type='submit' value='upload'> 	
</form>
```
i have such path written 
$router->map('POST','/admin/', 'class/admin.php', 'edited');
but when i try to catch the file with this code
if($_POST){
			print_r($_FILES);
	}
nothing happens
Thx

**Comment by sinkaszab** [comment]
I really don't think this is the best way to check if you have any '$_POST' array item set. Or is this just pseudo code?

**Comment by WingRS** [comment]
It is pseudo actualy, just to look if something happens. But in fact id does not work... Any ideas?

**Comment by sinkaszab** [comment]
Well if you inserted this line I would encourage you to log what actually gets executed.

**Comment by WingRS** [comment]
i think i do not unerstand you clearly, but when i upload the file, in result it prints empty Array()

**Comment by WingRS** [comment]
I just want to upload file to the server( i move it in procces to a folder), but $_FILES is empty, and i can't figure out why it is

**Comment by sinkaszab** [comment]
Please don't take that hard, but my point is that your problem has nothing to do with AltoRouter at all. It has to do with lack of knowledge of yours... That's why I advised you to somehow log what happens during execution, check your error logs that you can get closer to understand where your code fails.

**Comment by koenpunt** [comment]
How do you handle the matching route? Because from your code I think you expect the file in the third param to be included, but this completely depends on your route handler.

**Comment by WingRS** [comment]
@koenpunt so how i should handle the matching route to catch the file?

**Comment by koenpunt** [comment]
Have a look at; http://altorouter.com/usage/matching-requests.html

**Comment by WingRS** [comment]
Hey, it's me again. I have installed Jquery Upload Plugin and tried it out. It fails with an erorr like 
POST http://yourdomain/g/server/php/ 404 (Not Found)
send @ jquery.min.js:5
ajax @ jquery.min.js:5
send @ jquery.fileupload.js:906
_onSend @ jquery.fileupload.js:968
(anonymous) @ jquery.ui.widget.js:127
data.submit @ jquery.fileupload.js:674
(anonymous) @ basic-plus.html:144
dispatch @ jquery.min.js:4
r.handle @ jquery.min.js:4

**Comment by koenpunt** [comment]
Probably a rewriting issue. Because I don't see you outputting a 404, so that's probably a server error.
Do GET requests work?

**Comment by mastacontrola** [comment]
I believe, if uploading a file via another tool, you typically need to use something like:

```
<?php
$vars = file_get_contents('php://input');
// If json uploaded then do:
$vars = json_decode($vars, true); // True = make it into array so you can access as $vars['label1'];
```

**Comment by WingRS** [comment]
Thanks guys!
I already have solved the issue, by editing my controllers.

**Comment by CristopherJonas** [comment]
@WingRS Please show us your solution.  =)

**Comment by ErikThiart** [comment]
@WingRS as @CristopherJonas said, please show us your solution. It will help others who encounter the same issue and just make the internet a better place for all.
