### ISSUE TITLE
Why is so slow?

### ISSUE THREAD

**Issue by anthoniussk** [dannyvankooten/AltoRouter#179]
Hi, I am looking for an controller and I found AltoRouter. I compiled small test with AltoRouter by extending FastRouter vs TreeRouter benchmark (https://github.com/baryshev/FastRoute-vs-TreeRoute). And result is so worst:

FastRoute init time: 0.095005989074707
TreeRoute init time: 0.029001951217651
AltoRoute init time: 0.0080001354217529
FastRoute first route time: 0.74104046821594
TreeRoute first route time: 0.67903804779053
AltoRoute first route time: 1.1710677146912
FastRoute middle route time: 1.2280716896057
TreeRoute middle route time: 1.0190601348877
**AltoRoute middle route time: 18.275044202805**
FastRoute last route time: 1.960104227066
TreeRoute last route time: 1.0540637969971
AltoRoute last route time: 34.506975412369
FastRoute not found time: 1.7030992507935
TreeRoute not found time: 0.61503458023071
**AltoRoute not found time: 29.047660827637**

Am I do something wrong or the AltoRouter is so slow??

Source code here (can't attach to post): http://www.softpae.com/router_test.zip

**Comment by koenpunt** [comment]
Please create an example repo with the source if you want to demonstrate is. So that it's not required to download the source if one only wants to view the code. Thanks!

**Comment by anthoniussk** [comment]
Sorry, not interested to create repo for all small things I do, so forget it. ;) (in peace)

I found it have classic routers problem with lot of routes and lot of regex lookups and stripos/strncmp lookups that FastRoute router fix by it special regex algorithm. I tested some others routers and all routers with this "foreach-route" algorithm have this same problem, only TreeRouter and FastRoute uses different algo, so working faster.

It could be interesting to combine tree algo with foreach, simply by split routes array to more routes arrays for each number of URI parts (/) (inside map function) and then do lookup only on appropriate routes arrays.

**Comment by koenpunt** [comment]
> Sorry, not interested to create repo for all small things I do, so forget it.

Then you will understand that I'm not going to download stuff for issues that people create.

So I'm going to close this now, but I'm happy to reopen if you supply some more info.

Thanks.

**Comment by michielvv** [comment]
As I was interested to see if I could contribute to this, I've actually downloaded the zip with benchmarks.  However, if I read the code correctly the benchmarks  init times are for a single initialization, while the matches  are for 10000 repeated matches.   

So if you take into a account that in a real life situation you usually  do 1 initialisation + 1 match per request, plus the fact that compiled regexes are cached by php,  doing 1 init + 10000 repeats on the same match makes no sense for a benchmark like this.

A good benchmark should at least take into account a real http request,  and should probably also include FastRoute's caching ability.  My guess would be that routing time is pretty much neglectable for any sensible amount of routes.

**Comment by anthoniussk** [comment]
@michielvv Yes, you are right, partially. Partially because routers does not do 1 match per request, there is not too much application that uses only one route, so if you have defined more than one route, you loop through more than one route, potentially through all routes, so there is the time for lookup algo. Especially in AltoRouter, because it does not know optional parameters, so you can't create one route for all controller/actions. But your point about initialisation is correct. This script is benchmarking lookup algo only, so I rewrote it to test routers closely to real situation.

Right now I tested 40 routes including static route and with router initialisation included for each "request". Surprised by FastRouter with simpleRouter (non-cached) - is so slow because of initialisation. So, the result is much more interesting then before:

FastRoute init time: 0.039002895355225
FastRouteCached init time: 0.0070011615753174
TreeRouteCached init time: 0.0019998550415039
AltoRoute init time: 0.0019998550415039
AltoRouteCached init time: 0.0010001659393311
SimpleRouteCached init time: 0.0070009231567383

FastRoute first route time: 10.98562502861
FastRouteCached first route time: 0.74304127693176
TreeRouteCached first route time: 0.51102733612061
AltoRoute first route time: 0.46102571487427
AltoRouteCached first route time: 0.38702201843262
SimpleRouteCached first route time: 1.1010637283325

FastRoute middle route time: 10.834619283676
FastRouteCached middle route time: 0.67004036903381
TreeRouteCached middle route time: 0.73003888130188
AltoRoute middle route time: 0.97305822372437
AltoRouteCached middle route time: 1.0740642547607
SimpleRouteCached middle route time: 0.94705605506897

FastRoute last route time: 10.530603170395
FastRouteCached last route time: 0.76904368400574
TreeRouteCached last route time: 0.84204983711243
AltoRoute last route time: 1.5540883541107
AltoRouteCached last route time: 1.5780909061432
SimpleRouteCached last route time: 0.96405649185181

FastRoute not found time: 10.660607814789
FastRouteCached not found time: 0.71504044532776
TreeRouteCached not found time: 0.69704079627991
AltoRoute not found time: 1.2690715789795
AltoRouteCached not found time: 1.3260765075684
SimpleRouteCached not found time: 0.92205381393433

Conclusion: AltoRouter is usable if you does not require optional parameters. It is still slower than cached FastRoute or TreeRoute, but not so slow in real environment.

@koenpunt ... sure, if uploading is only the one problem, you could close what you want :) And because I found answers, you could keep it closed, I was here to solve problem not to discus about working styles :-)
