### ISSUE TITLE
not working target and name 

### ISSUE THREAD

**Issue by beoro** [dannyvankooten/AltoRouter#180]
`$router->map( 'GET',  '/[a:language]',  function($language) {
   if(in_array($language, array('en', 'fr' ,'de'))){
       echo $language;
   }
   return true;
});

$router->map('GET', '/',  'controller_user',  'getIndex');
$router->map('GET', '/[a:language]',  'controller_user',  'getIndex');

$match = $router->match();

Not target and name

print_r($match['target']);
print_r($match['name']);`

**Comment by koenpunt** [comment]
Not sure what you're trying to do, but you can't define a route with the same name twice. 
Do you have php error display enabled?

**Comment by mastacontrola** [comment]
While I can understand wanting to have the same name to a named route, I also understand why this is the case. (at least now).

Maybe change your code to read:
```
$router->map( 'GET', '/[a:language]', function($language) {
if(in_array($language, array('en', 'fr' ,'de'))){
echo $language;
}
return true;
});

$router->map('GET', '/[a:language]?/?', 'controller_user', 'getIndex');

$match = $router->match();

Not target and name

print_r($match['target']);
print_r($match['name']);
```
Notice the ? marks.  You might also need to apply the patch found from issue #99 at the end to do the 'multi-optional' fix to do this properly.

**Comment by koenpunt** [comment]
The questionmark after the last slash will have no effect, they only affect the parameters. 

To only match certain paths (language codes in your case) you can already define those in the route like so:

```php
$router->map('GET', '/[en|fr|de:language]?', 'controller_user', 'getIndex');
```

And with it being optional it will match with and without language to the same named route.

This however is pending a bugfix (#99)

**Comment by mastacontrola** [comment]
The reason I add /? Is from what I've seen some browsers auto append a trailing slash if there isn't a file extension and or query type strings. Meaning if you went to /en/ the route would fail. Adding the /? Allowed the route to pass either as /en or /en/

**Comment by koenpunt** [comment]
I understand your reasoning, but I'm saying that it's not how AltoRouter works; in only interprets the `?` for parameters, with potential preceding `/`.
