### ISSUE TITLE
Do I need to map every single page with AltoRouter

### ISSUE THREAD

**Issue by manishbathla** [dannyvankooten/AltoRouter#181]
Hi, 

this is mapping

> $router->map('GET','/', 'home.php', 'home');
> $router->map('GET','/home/', 'home.php', 'home-home');
> $router->map('GET','/plans/', 'plans.php', 'plans');
> $router->map('GET','/about/', 'about.php', 'about');
> $router->map('GET','/contact/', 'contact.php', 'contact');
> $router->map('GET','/tos/', 'tos.html', 'tos');

Scenario: I have 100 pages or round about 50 controllers on my website. 

Question: Do I need to map each and every page and all 50 controllers on website to get AltoRouter working? or are there any short cuts/ Wildcard like check if there is a page or controller available and then load it or else show 404?

I posted a question on stackoverflow regarding AltoRouter, will be glad if you can take a look at this too.
[](http://stackoverflow.com/questions/41713414/is-this-how-altorouter-get-post-method-work)

**Comment by mobihack** [comment]
The way i set up things was something like this:

> I have set up in a framework model (MVC). As posting those codes will over-complicate the answer i had created a small code.

> Routes.php

`<?php
return(
	array(
		array('GET', '/', 'index.php'),
		array('GET', '/author/[:author]/', 'author.php'),

		array('GET', '/admin/', 'admin.php'),
        	)
	);
?>`

> app.php
`<?php
$router = new \Shatter\AltoRouter();
        $router->setBasePath(INSTALLDIR); //Using router in sub folder
        $router->addRoutes(require ('Routes.php'));
        //Now Routes have been added
        $matches=$router->match();
        if( $matches ) {
        include($matches['target']);
        }
?>`

**Comment by koenpunt** [comment]
AltoRouter lets you free to do such things any way you want.

@mobihack's approach is a good start, but you can also extend that to something more flexible;

```php
$router->map('/[:controller]/[:action]?/[:id]?', function($controller, $action = 'index', $id = null) {
  // map controller string to class and call action on it
});
```
