### ISSUE TITLE
Nothing happens 

### ISSUE THREAD

**Issue by Bram-Zijp** [dannyvankooten/AltoRouter#182]
Tried installing with composer and manually running locally with WAMP php 5.6.x but can't get any of the routes to fire. Tried mapping with vhosts and such but no response is ever made.

```
require 'AltoRouter.php';
$router = new AltoRouter();
$router->map( 'GET', '/', function() {
    echo 'lol';
});
```

**Comment by manishbathla** [comment]
you forgot to add

$match = $router->match();

// call closure or throw 404 status
if( $match && is_callable( $match['target'] ) ) {
	call_user_func_array( $match['target'], $match['params'] ); 
} else {
	// no route was matched
	header( $_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');
}

**Comment by koenpunt** [comment]
Closing because of no response of OP
