### ISSUE TITLE
Performance improvement: Radix-ish tree for HTTP methods

### ISSUE THREAD

**Issue by dannyvankooten** [dannyvankooten/AltoRouter#187]
To speed up route matching it might make sense to move to a Radix tree-ish approach. While a full blown Radix tree is probably not suited for PHP unless we write to a file somewhere, a quick & easy win might be to split up the `AltoRouter::$routes` array into separate keys for each HTTP method.

This way, we do not have to loop through routes and compare the HTTP method which should slightly speed up the match process, especially for non-existing routes or routes other than the most commonly used `GET`. 

**Cons**
- `getRoutes()` currently exposes the internal routes array, so this would most likely mean a BC break. Not sure if that's even worth the potential gain.
- AltoRouter accepts multiple HTTP methods, which means possibly storing a route more than once. We already do this for the `$namedRoutes` array though and PHP uses [copy-on-write](http://www.phpinternalsbook.com/zvals/memory_management.html), so this should not be an issue really.

**Comment by dannyvankooten** [comment]
Running `php tests/benchmark.php` for matching 1000 routes with this change yields the following results.

**master**
```
Time: 0.1864 seconds
Peak memory usage: 2MB
```

**http-method-subkeys**
```
Time: 0.0451 seconds
Peak memory usage: 2MB
```

This is for 1000 random routes with 1000 random requests (and random methods) though, so not super representable of a real use case probably.

**Comment by dannyvankooten** [comment]
@koenpunt what are your thoughts on this, worth it? Would be cool to test on a "real" set of routes.

This would be easier to implement if we didn't expose the internal routes array, but perhaps we can stick to a flattened array for the `getRoutes()` return value while internally we use the HTTP method tree. The memory implications of storing both should be minimal because of PHP's copy-on-write behavior.

**Comment by mastacontrola** [comment]
I see one problem with your isset($this->routes[$method]) statement.

You're trying to flatten out which is great, but you're setting method before method is even flattened.

Not that it's a huge deal, but you are essentially, outside the loop, creating an array with ALL methods, and you're not checking if it's set within the loop to predefine the type.

maybe something like:
```
         $methods = explode('|', $method);
         foreach ($methods as $method) {
             if (!isset($this->routes[$method])) {
                 $this->routes[$method] = array();
             }
             $this->routes[$method][] = array($route, $target, $name);
         }

```

**Comment by koenpunt** [comment]
@dannyvankooten will take a good look this weekend.

**Comment by dannyvankooten** [comment]
Good catch @mastacontrola, should be fixed in ed6404fc38a0e12aa4f483d02d8b24ef8d5bfd1f .

**Comment by mastacontrola** [comment]
I've updated my fork of this to include many things. I would love to do a pull request, but realize I HAVE A TON OF CHANGES. (Sorry but i think the caps are needed.)

I've modified the "tests" so that they're not commented and the tests appear to be working properly.

Of note, my version has been namespaced to ensure portability so my tests and benchmark files are suited to that.

Maybe you can take a look.  I would love to port my changes in, but i realize I have a TON of them.

https://github.com/mastacontrola/AltoRouter

**Comment by mastacontrola** [comment]
So I decided to put it in there but again i totally understand it not being pulled right away and/or being closed due to not being able to track.

**Comment by mastacontrola** [comment]
So my pull request has been closed, but of note, I don't know if you want to update the benchmark to make the flow a little bit more proper for testing?

Right now the benchmark.php is calling the requestRandomMethod and requestRandomUrl functions X number of iterations.  While loops of 1000 are relatively quick, wouldn't it make more sense to create your "random" items outside of a loop, and lose the need for additional function calls where needed?

I know my benchmark is not necessarily better than what you had but from a flow standpoint I found it to be extremely slow.

How I went around 1000 function calls (in the loop) (or x function calls with CLI Arg):

```
require __DIR__.'/../vendor/autoload.php';
global $argv;
// $n = number of times to repeat
$n = isset($argv[1]) ? intval($argv[1]) : 1000;
// $length = number of characters in url string.
$length = isset($argv[2]) ? intval($argv[2]) : 20;
/**
 * Generates a random request url.
 *
 * @param int $length Length of the url.
 * @param int $n      Total of routes to make.
 *
 * @return array
 */
function randomRequestUrl($length = 20, $n = 1000)
{
    $characters = '0123456789abcdefghijklmnopqrstuvwxyz/';
    $charactersLength = strlen($characters);
    $randomString = '/';
    $routes = array();
    for ($i = 0; $i < $n; $i++) {
        for ($j = 0; $j < $length; $j++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        $routes[] = $randomString;
        $randomString = '/';
    }
    return $routes;
}
$methods = array(
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'GET|POST',
    'PUT|POST',
);
while (count($methods) <= $n) {
    $methods = array_merge(
        $methods,
        $methods
    );
}
$methods = array_slice($methods, 0, $n);
$randkeys = array_rand($methods, $n);
$routes = randomRequestUrl($length, $n);
$router = new AltoRouter();
// benchmark map method.
$start = microtime(true);
// Perform mapping
for ($i = 0; $i < $n; $i++) {
    $router->map(
        $methods[$randkeys[$i]];
        $routes[$i],
        'string'
    );
}
$end = microtime(true);
// Print time info for mapping.
echo "Time: Mapping "
    . number_format(($end - $start), 4)
    . ' seconds'
    . PHP_EOL;
echo "Peak Memory Usage: "
    . (memory_get_peak_usage(true) / 1024)
    . 'KiB'
    . PHP_EOL;
// benchmark match method
$start = microtime(true);
// Perform matching
for ($i = 0; $i < $n; $i++) {
    $router->match(
        $routes[$i],
        $methods[$randkeys[$i]]
    );
}
$end = microtime(true);
// Print time info for matching.
echo "Time: Mapping "
    . number_format(($end - $start), 4)
    . ' seconds'
    . PHP_EOL;
echo "Peak Memory Usage: "
    . (memory_get_peak_usage(true) / 1024)
    . 'KiB'
    . PHP_EOL;
```

I realize this will probably not change the time the benchmark must work to do actions, but I think it's still better than calling a custom function X number of times.  We prepare our information before we begin testing and I think things will be presented to the user in a more "real-world" ideology.

**Comment by mastacontrola** [comment]
Understand my thoughts are simply so we can benchmark what we want as we need to. So map is a method within the calling class element, we probably should allow "benchmarking" it as well as the match.

I understand the match, due to the compileRoute method, is the biggest "hog" of resources, but at least in the suggested form you could benchmark any of the given AltoRouter methods as seen fit.

**Comment by dannyvankooten** [comment]
Hey @mastacontrola,

That definitely makes sense. The benchmark has been thrown together mainly to test the "match" part and the additional time it takes for the function calls etc. is not that important as we're not benchmarking AltoRouter really, we're just benchmarking differences in the match logic. That said, I agree that it's probably better to prepare first & then test in a little more isolation. Will try to cherry-pick that from your list of commits soon-ish.

**Comment by mastacontrola** [comment]
Here's the "cherry picked" commit if you needed it.

https://github.com/mastacontrola/AltoRouter/commit/f357bc9f76312141413e4ebdc30fe57b0d34cb1b

**Comment by dannyvankooten** [comment]
I just updated the benchmark to be a bit more representable of a real use case by preparing first (thanks @mastacontrola), then mapping **n** routes & then matching only a known and unknown (worst case) route. 

The results are pretty telling, as even this minor change to the `map` method adds a considerate amount of time that adds up and basically dwarves the performance improvement in the `match` method.

**master**
```
Map time: 0.002294 seconds
Match time (known route): 0.000163 seconds
Match time (unknown route): 0.002001 seconds
Total time: 0.004458 seconds
Memory usage: 6606KB
Peak memory usage: 8192KB
```

**http-method-tree:**
```
Map time: 0.005010 seconds
Match time (known route): 0.000029 seconds
Match time (unknown route): 0.000433 seconds
Total time: 0.005472 seconds
Memory usage: 8657KB
Peak memory usage: 10240KB
```

This is probably mostly due to c84b32cc2a3e1cb4ad916ae221f7c39e9a711cb3 where we store the route in multiple places to preserve backwards compatibility, but all in all it does not seem worth it. 

A full blown radix tree where we write the optimised router map to some cache would still be fun to write, but right now I think AltoRouter is fast enough as it is, despite the linear performance cost (it beats the default Symfony router, AuraRouter and several more).
