### ISSUE TITLE
AltoRouter Not calling Controller

### ISSUE THREAD

**Issue by 69-69** [dannyvankooten/AltoRouter#190]
thank great work.
I have a controller called 'IndexController' with it methods which reside in a directory or folder called 'AllControllers'.
But any time I route it using 'altorouter;' it gives error as: can not call IndexController#display_item. Below is a code snippet:

`$router = new AltoRouter();
$router->setBasePath('');
$router->map('GET', '/', 'IndexController#display_item', 'Index');
$router->map('GET', '/content/[:parent]/?[:child]/?[:grandchild]?', 'contentController#display_item', 'content');
$match = $router->match();

if ($match === false) {
    echo "// here you can handle 404 \n";
} else {
    list($controller, $action) = explode('#', $match['target']);
    if (is_callable(array($controller, $action))) {
        call_user_func_array(array($controller, $action), array($match['params']));
    } else {
        echo 'Error: can not call ' . $controller . '#' . $action;
        // here your routes are wrong.
        // Throw an exception in debug, send a  500 error in production
    }
}`

I need a thorough help. Thank you

**Comment by koenpunt** [comment]
Have you checked out the website? http://altorouter.com

**Comment by stephenaryee** [comment]
yes I have. But it did answer my question

**Comment by mastacontrola** [comment]
So looking at your code, is `$controller` a class that's needs to be loaded first?
I'm just guessing we're not seeing the full code handling this. Maybe requiring the controller by instantiating may help as well?

I'm guessing `$controller` is a class that should be called but in this case it simply isn't.

Maybe before the `if(is_callable(` you instantiate the controller object with something like: `$controller = new $controller;`

**Comment by mastacontrola** [comment]
```
$router = new AltoRouter();
$router->setBasePath('');
$router->map('GET', '/', 'IndexController#display_item', 'Index');
$router->map('GET', '/content/[:parent]/?[:child]/?[:grandchild]?', 'contentController#display_item', 'content');
$match = $router->match();

if ($match === false) {
    echo "// here you can handle 404 \n";
} else {
    list($controller, $action) = explode('#', $match['target']);
    $controller = new $controller;
    if (is_callable(array($controller, $action))) {
        call_user_func_array(array($controller, $action), array($match['params']));
    } else {
        echo 'Error: can not call ' . get_class($controller) . '#' . $action;
        // here your routes are wrong.
        // Throw an exception in debug, send a 500 error in production
    }
}
```

**Comment by stephenaryee** [comment]
great to you all. I have being able to solve it; I sort it in the last 24 hours ago.
 thanks to you all

**Comment by mastacontrola** [comment]
Would you mind describing what you did to fix it and possibly marking this issue as closed so people know it's not something awaiting action?
