### ISSUE TITLE
Map home controller with altorouter.

### ISSUE THREAD

**Issue by manishbathla** [dannyvankooten/AltoRouter#197]
I have home controller in my directory app>controller, it's a class with method index. I need to map it with AltoRouter. 

> $router->map('GET','/', 'Home#Index', 'home');

How do I do this? 

Is the code below even right?

```
$router->map( 'GET', '/', function( $controller = 'Home', $action = 'Index' ) {  
    if( method_exists( $controller, $action ) ) {
        $controller::Index();
    }else{
        echo 'missing';
}})
```

**Comment by Vankerkom** [comment]
This isn't considered an issue related to AltoRouter.

Read [this](http://altorouter.com/usage/matching-requests.html) example, the target can return anything you specify. In this case you can map a route like this.

`$this->router->map('GET', '/', 'HomeController');
$this->router->map('GET', '/', 'HomeController@magic');`

And in your process method you implement something like this:

`$this->match = $this->router->match();

if (stripos($this->match['target'], '@') !== false) {
    list($controller, $method) = explode('@', $this->match['target'], 2);
} else {
    $controller = $this->match['target'];
    $method = 'index';
}`

**Comment by koenpunt** [comment]
@manishbathla I think @vanderkom answers it just right.

**Comment by manishbathla** [comment]
Thank you sir, I will go through them all and get back to you guys ...
thank you again.
