### ISSUE TITLE
Getting 404 error on xampp

### ISSUE THREAD

**Issue by mahyar78** [dannyvankooten/AltoRouter#198]
Hi,

I just tried to use Alto yesterday but couldn't reach any success.

anything I map in my router would get 404 error(as you've explained in comment it means nothing matched)

you know I'm working on a folder in htdocs folder called "caspian" and the url is localhost/caspian..

I've set the base path to /caspian/ but again didn't catch the goal.

where's the problem?

I've done the installation by you guide...

**Comment by ErikThiart** [comment]
What does your `.htaccess` file look like?
