### ISSUE TITLE
Whatever I specify in the closure doesn't happen

### ISSUE THREAD

**Issue by rjquery** [dannyvankooten/AltoRouter#201]
Greetings. I'm trying to use AltoRouter in a subfolder, and it matches, but the code inside of the closure doesn't run.

```
$router = new AltoRouter();
$router->setBasePath('/new');
$router->map('GET|POST','/', function(){
	echo 'This code runs'; //or even die('It died!'); doesn't work at all
}, 'home');

// match current request
$match = $router->match();
?>
```
```
<h1>AltoRouter</h1>

<h3>Current request: </h3>
<pre>
	Target: <?php var_dump($match['target']); ?>
	Params: <?php var_dump($match['params']); ?>
	Name: 	<?php var_dump($match['name']); ?>
</pre>
```

Result:

  | <h1>AltoRouter</h1>
-- | --
  |  
  | <h3>Current request: </h3>
  | <pre>
  | Target: <pre class='xdebug-var-dump' dir='ltr'>
  | <small>E:\wamp64\www\Websites\Development\haiaambiental.com.br\public\new\index.php:19:</small>
  | <b>object</b>(<i>Closure</i>)[<i>2</i>]
  | </pre>	Params: <pre class='xdebug-var-dump' dir='ltr'>
  | <small>E:\wamp64\www\Websites\Development\haiaambiental.com.br\public\new\index.php:20:</small>
  | <b>array</b> <i>(size=0)</i>
  | <i><font color='#888a85'>empty</font></i>
  | </pre>	Name: 	<pre class='xdebug-var-dump' dir='ltr'>
  | <small>E:\wamp64\www\Websites\Development\haiaambiental.com.br\public\new\index.php:21:</small><small>string</small> <font color='#cc0000'>'home'</font> <i>(length=4)</i>
  | </pre></pre>

Any help would be greatly appreciated.

**Comment by koenpunt** [comment]
You have to call the closure yourselves;

```php
$match[‘target’]();
// or
call_user_func_array($match[‘target’], $match[‘params’]);
