### ISSUE TITLE
[feat] Rate limiting

### ISSUE THREAD

**Issue by jarodium** [dannyvankooten/AltoRouter#207]
Hello

I would like to request a rate limiting feature for AltRouter.
It may not be anywhere related to the routing per se, but I would be a great addition.

**Comment by YannickFricke** [comment]
No it wouldnt be a great addition, because rate limiting is a feature of your application and doesnt depends on the router

**Comment by koenpunt** [comment]
This is definitely not a feature for an application router. You should probably implement this at server level (nginx, Apache, etc) or in php before you handle a request with AltoRouter.
