### ISSUE TITLE
question about the code

### ISSUE THREAD

**Issue by ncou** [dannyvankooten/AltoRouter#208]
Hi,

very nice and clean lib. Looking at the code, i got a question about this line : https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L226

It looks like a dirty patch, to remove the param if it's name is numeric. Can you explain me in which cases this could happen ? perhaps if there is a problem in the regex ? 

thank for enlightning me :)

**Comment by koenpunt** [comment]
This is because `preg_match` includes matches twice; once by their name, and once with the numeric index. So for this reason we strip the numeric keys, since all the required params are named.
