### ISSUE TITLE
How to return 404 page if request doesn't match in map?

### ISSUE THREAD

**Issue by x4warrio** [dannyvankooten/AltoRouter#210]
How can i return 404 Page not found if request doens't match any map ?

**Comment by tafelglotzer** [comment]
You could do something like this:
```
$match = $router->match();

if (! $match) {
    require '404.html';
}
```

**Comment by x4warrio** [comment]
I've tried this, but contents of 404 page will be displayed at the end of page when routes matched!
![screen shot 2017-12-10 at 10 27 58 pm](https://user-images.githubusercontent.com/33950479/33806341-6a33d544-ddf9-11e7-9401-8bd6dd937470.png)

any idea?

**Comment by x4warrio** [comment]
I found my temporary solution is add exit function end of view controller then the 404 page contents will not be displayed anymore!

**Comment by koenpunt** [comment]
@tafelglotzer’s suggestion is correct. But the details will depend on your actual implementation
