### ISSUE TITLE
mapping/routing controllers in sub folders

### ISSUE THREAD

**Issue by manishbathla** [dannyvankooten/AltoRouter#211]
I have all my controllers divided in sub-folder. Like

> app/controller/common/HomeController.php
> app/controller/common/HeaderController.php
> app/controller/common/FooterController.php
> app/controller/info/ContactController.php
> app/controller/info/AboutController.php

How do I map and call these controllers?. Is there a way of doing it?

**Comment by manishbathla** [comment]
Is this right ?

```
$router->map('GET', '/', function($controller = 'Home', $action = 'index') {
    if(method_exists($controller, $action)) {
        $controller::$action();
    } else {
        echo 'i miss home';
    }
});

```

**Comment by koenpunt** [comment]
Since the whole mapping of urls to actual controllers is not the responsibility of AltoRouter I've closed the issue. 

But in terms of documentation; http://altorouter.com/ should get you started
