### ISSUE TITLE
Route not working

### ISSUE THREAD

**Issue by Sirjoseph94** [dannyvankooten/AltoRouter#212]
I really don't know what am doing wrong, but for some reason i keep getting 404 error. i guess the match wasn't found

--Route
```php
$router = new AltoRouter();

// map homepage
$router->map('GET', '/', function ($twig) {
    echo $twig->render('home.php.twig');
}, 'home');
$router->map('GET', '/contact/', function ($twig) {
    echo $twig->render('contact.php.twig');
}, 'contact');
$router->map('GET', '/quote/', function ($twig) {
    echo $twig->render('request_quote.php.twig');
}, 'quote');
$router->map('GET', '/about/', function ($twig) {
    echo $twig->render('about.php.twig');
});
// match current request
$match = $router->match();
if ($match) {
    require $match['target'];
} else {
    header("HTTP/1.0 404 Not Found");
    echo $twig->render('404.php.twig');
};
```

--Htaccess
```
RewriteEngine on
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
```

**Comment by koenpunt** [comment]
What do you expect `require $match['target'];` does?

**Comment by Sirjoseph94** [comment]
To match and process the request. but currently, i keep getting error
i also tried
`// call closure or throw 404 status
if ($match && is_callable($match['target'])) {
    call_user_func_array($match['target'], $match['params']);
} else {
	// no route was matched
    header($_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');
}`

Still not able to get it to display any page but 404 not found error.

It seems not to be matching, what am i doing wrong?

**Comment by koenpunt** [comment]
The `call_user_func_array` example should work with the routes you registered. 

Are you running this code from the root of the domain? E.g. `http://example.com/contact/`, or is this code running in a subdirectory (e.g. `https://example.com/subsite/contact/`)? For the latter you will have to configure a "base path" using `setBasePath`; `$router->setBasePath('/subsite')`.


NB. I've updated the code formatting in your comments (you can use triple backticks for multiline code blocks; `` ``` ``)

**Comment by klikrzys** [comment]
I have the same problem, my routes don't match. I configured my Nginx server correctly. I've used similar code to issue publisher, but I didn't use that ```require $match['target'];``` part.

```
$router = new AltoRouter();

      // map homepage
      $router->map( 'GET', '/', function() {
          echo("works");
      });
      
      // map users details page
      $router->map( 'GET|POST', '/users/[i:id]/', function( $id ) {
         echo("works");
      });

      $match = $router->match();
      if ($match) {
         echo "match";
      } else {
          echo "No match";
      };
```

I've also checked url from php using ``` $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";``` and params looks good.

**Comment by koenpunt** [comment]
@klikrzys so you're saying it results in `No match`?
For the routes you defined, the functions will not automatically be called, you have to that yourself, e.g.;

```php
if ($match) {
    $match['target']();
}
```

**Comment by AVONnadozie** [comment]
Same issue here

```
$router = new AltoRouter();

//$router->setBasePath($config['basepath']);

$router->map('GET', '/', function() {
    echo 'Testing AutoRouter';
});

$router->map('GET', '/user/', 'userProfile');

$router->map('POST', '/user/', 'saveConfiguration');

$match = $router->match();

die($match);
```

I expected `die($match);` to display the content of `$match` or throw an error if it's content is not scalar but it displays nothing instead.
This happens for all routes.

**Comment by HewieWang** [comment]
Not working,I got blank page,No errors,no warnings,nothing.
Status Code:200
PHP/7.3.4
Apache/2.4.39
