### ISSUE TITLE
More detailed documentation ?

### ISSUE THREAD

**Issue by pramanadiputra** [dannyvankooten/AltoRouter#213]
Hi, 

Thank you for making this router library, I have read the documentation that is available on altorouter.com 
But for me the documentation is not detailed enough, and mostly makes me confused, specially on this part: 
http://altorouter.com/usage/mapping-routes.html (mapping routes). 

I have these following Group Routes: 

```php
$router->addRoutes(array(
    array("GET", "/user/", "Controllers\UserController@getListOfAllUsers", "List all User"),
    array("GET", "/user/[a]/", "Controllers\UserController@showUserProfilePage", "Get Userx Profile"),
    array("GET", "/user/[edit]", "Controllers\UserController@showEditAccountPage", "Edit Profile Account"),
    array("POST", "/user/[edit]/post/profile", "Controllers\UserController@updateTabProfile", "Post Edit User Profile"),
    array("POST", "/user/[edit]/post/akun", "Controllers\UserController@updateTabAccount", "Post Edit User Account"),
));
```

I want to make if user edit their account it will be on local.dev/user/edit, and when they check their or someone's else profile it will be on local.dev/user/{username} but now when I go to local.dev/user/edit it's  showing view profile page instead of editing profile page

The documentation on (mapping routes) is really confusing me, I don't even understand what does Match Types are. 

such as this example: 

`
/[a:c]/[a:a]?/[i:id]? | /controller/action/21 | $c: "controller", $a: "action", $id: 21
` 
*a* is 'a'  => '[0-9A-Za-z]++' but what is this 'action' means? the GET|POST|PATCH|PUT|DELETE ?

I have searched for tutorials, but there are really small amounts of examples and tutorials of using AltoRouter, even on its own documentation. 

I hope there will be more examples. 

Thank You

**Comment by dauni** [comment]
> /[a:c]/[a:a]?/[i:id]? | /controller/action/21 | $c: "controller", $a: "action", $id: 21

a:c means a variable $c will be filled with an alphanumerical value
a:a means a variable $a will be filled with an alphanumerical value
i:id means a variable $id will be filled with an integer

so an url /controller/action/21 will result in following values:
```php
$c='controller';
$a='action';
$id='21';
```

and a url /asdf/dada/432 will result in following values:
```php
$c='asdf';
$a='dada';
$id='432';
```

**Comment by koenpunt** [comment]
If you want to improve the documentation, please open a PR against the `gh-pages` branch.

**Comment by pramanadiputra** [comment]
@dauni Thank you for your explanation, it helps me uderstand it.
