### ISSUE TITLE
Calling the URL by Route Name?

### ISSUE THREAD

**Issue by pramanadiputra** [dannyvankooten/AltoRouter#214]
in $router->map, there are 4 parameters -> Method, Route, Target, and Name. And I wonder if I set a route as example: $router->map("GET", "/contact/team", "contactcontroller#contact", "contact") and I want to set this url "/contact/team", how can I call it by just the name? 

Thank You

**Comment by dannyvankooten** [comment]
Hi @pramanadiputra,

Sorry for being late to reply, I notice this isn't in the README or anything. We'll improve that.

You can get the URL for any named route by calling the `generate` function on your router instance, for example:

```php
$router = new AltoRouter();
$router->map( 'GET', '/contact', function() {
    // ...
}, 'contact' );
$contact_url = $router->generate( 'contact' ); 
```

Hope that clarifies!
