### ISSUE TITLE
Problem with GET methods

### ISSUE THREAD

**Issue by Talenvni** [dannyvankooten/AltoRouter#215]
Hi,

I have some issues when I want to pass GET methods in the url. 

Here my router 

> // Register when email received.
> 	$router->map( 'GET|POST', '/register?/[i:id]?/[a:token]?', function () {
> 			echo TwigCore::getLoad()->render( '/logon.twig', [
> 				'title'   => 'Inscription',
> 				'logon'   => LogonAction::signUp(),
> 				'message' => FlashCore::getFlash()
> 			] );
> 	}, 'register with email' );

So I have an id and a token to pass in the register page url in order to confirm a new user.

My function looks like 

> if ( isset($_GET['id'], $_GET['token']) ) {
> // some code to confirm
> else {
> return home
> }

In the url

> domaine.com/register/27/wOLc32o35D

no matter what I do, it doesn't run and return home.

Any idea ?

**Comment by koenpunt** [comment]
The URL parameters will not be provided through the `$_GET` superglobal.

Those parameters are available in the return value of ‘$router->match()`.

You probably want to do something like this;

```php
$match = $router->match();
if ($match) {
  call_user_func($match['target'], $match['params']);
}
``` 

That way the parameters are available as argument to your route function;

```php
$router->map( 'GET|POST', '/register?/[i:id]?/[a:token]?', function ($params) {
echo TwigCore::getLoad()->render( '/logon.twig', [
'title' => 'Inscription',
'logon' => LogonAction::signUp(),
'message' => FlashCore::getFlash(),
'params' => $params
] );
}, 'register with email' );
