### ISSUE TITLE
Resource render problem

### ISSUE THREAD

**Issue by iAyubAnsari** [dannyvankooten/AltoRouter#216]
`<?php 

require 'admin/vendor/AltoRouter.php';

$router = new AltoRouter();

$router->setBasePath('/a/news');
// $router->setBasePath('/a/news');

// map homepage
$router->map( 'GET |POST', '/', function() {
	require 'home.php';
});

$router->map( 'GET |POST', '/home', function() {
	require 'home.php';
});

// map user details page
$router->map( 'GET |POST', '/user/[i:id]/', function( $id ) {
	$er=$id;
	require 'users.php';
});

// match current request url
$match = $router->match();

// call closure or throw 404 status
if( $match && is_callable( $match['target'] ) ) {
	call_user_func_array( $match['target'], $match['params'] ); 
} else {
	// no route was matched
	echo "not found";
}
`
////////////////////////////////////////////////////////////////////////
'/' and '/home' routes are working fine.
but when i try accessing 'user/5/' url... file gets loaded but without css , js and other media resources.
please help
thanking you

**Comment by Eliepse** [comment]
Hi,
I think this is not an issue related to AltoRouter.

When loading your assets, you probably use an url like `href="css/style.css"` which use this entire current url to load it. As exemple, if you are in `http://domain.com/user/5`, it will try to load at `http://domain.com/user/5/css/style.css`.

To fix it, you can add a `/` at the start of your asset's url (i.e. `href="/css/style.css"`). This will tell the browser to load it from the root of your url. In this exemple, it will try to load `http://domain.com/css/style.css`.

Hope it will help you.

**Comment by koenpunt** [comment]
I agree with @Eliepse. If his suggestion doesn’t solve your problem please provide some more details and I will reopen the issue
