### ISSUE TITLE
Use a condition "OR" in routes ?

### ISSUE THREAD

**Issue by Talenvni** [dannyvankooten/AltoRouter#217]
Hi,

Juste a little question about the route target. Can I insert a condition in it ? Like a pipe "||" ?

Exemple 

$route->map('GET', '/form/[:insertUser] || /[:deletUser] || /[:connectUser] / etc.)

**Comment by visavi** [comment]
$router->map('GET',  '/form/[insertUser|deletUser|connectUser:method]', 'FormController');

**Comment by koenpunt** [comment]
What @visavi says ^
