### ISSUE TITLE
Not a issue more a routing question

### ISSUE THREAD

**Issue by telemoes** [dannyvankooten/AltoRouter#218]
Hi

It's not really a issue but i have q question...
Is there a way todo this much easier

```
$router->addRoutes(array(
    array('GET','/blog/index', 'blog#index'),
    array('GET','/blogcategories/index', 'blogcategories#index'),
    array('GET','/blog/create', 'blog#create'),
    array('GET','/blogcategories/create', 'blogcategories#create'),
    array('GET','/blog/[i:id]/edit', 'blog#edit'),
    array('GET','/blogcategories/[i:id]/edit', 'blogcategories#edit'),
    array('POST','/blog/store', 'blog#store'),
    array('POST','/blogcategories/store', 'blogcategories#store'),
    array('GET|POST', '/blog/[*:name]', 'blog#front')
));
```
And how must i do the followthing
www.domain.com/this-is-a-seo-url-howto
When there is no slash after the domain it is a url then it must go to the controller pages how make i this rule?
Sorry for my bad english.

Thx

**Comment by bennetgallein** [comment]
You mean like this:

www.domain.comthis-is-a-seo-url-howto

?

**Comment by telemoes** [comment]
Yes but with the slash after the extension ;) www.domain.com/this-is-a-seo-url-howto

**Comment by telemoes** [comment]
How must i make the route for this url

www.domain.com/this-is-a-seo-url-howto
```
$router->addRoutes(array(
array('GET','/blog/index', 'blog#index'), //admin blog index this works
    array('GET', '[*:name]', 'blog#front') // front
));
```
So how make i the route that 'this-is-a-seo-url-howto' goes to blog#front and that blog/index still goes to blog#index.

**Comment by telemoes** [comment]
But the url: this-is-a-seo-url-howto is for every blog post different.

**Comment by bennetgallein** [comment]
then by using a regex.. That's the only way I can imagine it to work :)

**Comment by telemoes** [comment]
$router->addMatchTypes([
    'slug' => '[0-9A-Za-z_-]++',
]);

$router->addRoutes(array(
    array('GET|POST', '/[slug]', 'pages#front'),
    array('GET|POST', '/blog/[slug]', 'blog#front')
));

WORKS!! thx
