### ISSUE TITLE
Problem with dash in route definition

### ISSUE THREAD

**Issue by cedrik75** [dannyvankooten/AltoRouter#219]
I am experiencing problem with this route definition.

```php
$router->map('GET','/[cs|en:lang]/accommodation/[i:id]-?[*:url]?/[*:section]?', 'detail.php');
```
When I visit this URL `http://www.mydomain.com/en/accommodation/123-best-hotel` the response header is `302` not `200`.
Do I have any mistake in the route definition? Maybe it is because of dash `-` after `[i:id]`?

Thank you for any suggestion.

**Comment by cedrik75** [comment]
> AltoRouter does not set any response headers, so the 302 and 200 are not from AltoRouter.

Thank you for this mention, which led me to the right direction. I had an error in Apache .htaccess file (old rule before using AltoRouter). Now everything works just fine.

**Comment by koenpunt** [comment]
Glad you figured it out!
