### ISSUE TITLE
Make benchmark

### ISSUE THREAD

**Issue by dejurin** [dannyvankooten/AltoRouter#224]
It's interesting to see how your framework behaves in the load in comparison with other similar framework.
Use: https://github.com/kenjis/php-framework-benchmark

**Comment by ellisgl** [comment]
Well it's not a framework, since it's just a router. =) Could just do a PHPBench setup to compare routers.

**Comment by dannyvankooten** [comment]
Hi @dejurin,

I wouldn't worry about it. Routing is very unlikely to be the bottleneck of your application and AltoRouter is as fast as a router can be in PHP.   

If you need raw speed, you'd be better off switching to a different language entirely or shortcutting the request that needs the performance boost.
