### ISSUE TITLE
Not intercepting google oauth callbacks

### ISSUE THREAD

**Issue by sfinetti** [dannyvankooten/AltoRouter#225]
Hi, I don't think this is a real issue but is something I didn't understand on the documentation (my fault, probably)

I created a sort of wildcard mapping for my front controller using AltoRouter that is working very smoothly except for oauth callbacks from google.

This is my mapping:
```
$router->map('GET|POST|PATCH|DELETE', '/[:controller]?[/]?[:action]?[/]?[:param]?', function($controller = 'dashboard', $action = 'index', $param = null) use($fullData) {
    if (empty($controller)) { $controller = 'dashboard'; };
    $pageName = '/'.$controller; 
    $fullData['pageName'] = $pageName;
    $controllerName = ucfirst($controller).'Controller'; 
    $contAction = $action.'Action'; 
    $controllerClass = new $controllerName($fullData);
    $fullData['LOG']->writeEntry('bootstrap.log', 'Routing Result', 'DEBUG', "Route created: {$controllerName}->{$contAction}({$param})");
    
    $controllerClass->$contAction($param);
});
```

As you can see it automatically gets controller, action and parameters, with the last 2 being optional.

The problem is that when I try to use google oauth service, pointing at my site on /oauth/google (so OauthController with googleAction(), there is no way to get $params populated.

google responds to the callback with /oauth/google?code=xxxxxxxxxxx. The router correctly reads controller and action, but completely misses the param. I Tried changing the callback url to /oauth/google/ with the trailing slash, but still it doesn't get $param. I'm quite at loss at understanding the problem. Could be just a regex matching issue, but I can't understand why it just "cut" the uri after the action and ignores the rest.

**Comment by sfinetti** [comment]
Well I actually solved going "around" the problem. Create a callback page which is served directly by apache, gets the token from google and pass it as /controller/action/param correctly formatted.

I'm still baffled on why it didn't work, though.

**Comment by koenpunt** [comment]
Params after the question mark are called "query params", and are not part of the path of a url. Query parameters can be retrieved from the global `$_GET` array. So in this case `$_GET['code']` would give you the value you want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
