### ISSUE TITLE
AltoRouter not doing the routing correctly

### ISSUE THREAD

**Issue by schuesslerf** [dannyvankooten/AltoRouter#227]
I'm just developing a little WebApp with PHP.

So far, I was only developing and testing offline, so on my localhost. Now, to see the behaviour on a server, I uploaded my code, fixed the database connection to fit for the MySQL-Server running on the server (which is Ubuntu 14.04) and tried to get it started.

First, what I'm doing for the routing, is a simple .htaccess, looking like that:

```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.php [L] 

```
And then, in my index.php, the routing is done

```
<?php 

include 'vendor/altorouter/altorouter/AltoRouter.php';

$router = new AltoRouter();
$router->setBasePath('');

$router->map('GET','/','home.php','home');
$router->map('GET','/datenschutz','datenschutz.php','datenschutz');
$router->map('GET','/impressum','impressum.php','impressum');

$router->map('GET','/header','header.php','header');
$router->map('GET','/jquery','vendor/components/jquery/jquery.js','jquery');
$router->map('GET','/bootstrapjs','vendor/twbs/bootstrap/dist/js/bootstrap.js','bootstrapjs');
$router->map('GET','/bootstrapcss','vendor/twbs/bootstrap/dist/css/bootstrap.css','bootstrapcss');
$router->map('GET','/generalStyle','style.css','generalStyle');
$match = $router->match();
if($match) {
  if($match['name'] === 'generalStyle'){
    header("Content-Type: text/css");
    $fileName = $match['target'];
    echo file_get_contents($fileName);
    return;
  }
  require $match['target'];
}
else {
  header("HTTP/1.0 404 Not Found");
  require '404.php';
}

?>
```
This is perfectly working on my localhost, so there doesn't appear to be a problem in general.

However, on my server, when heading forward to the IP, it first seems, that it's working, because when only going to /, the home.php file is loaded correctly. But, whatever other route I call, like /impressum, it's not working, going back to /, the home.php is working again.

Now, replacing home.php (in the route) with impressum.php is working as well, then I can see the correct file as well.  --> It's always only the "/" route, that's working...

Does anybody have an idea, why this happens or what the problem is?

I tried to call the files directly, and (besides some scripts not loaded etc.) its working, so going to myDomain.com/impressum.php is working fine, so it doesn't seem to be a problem of the file or sth.

I also tried to set the permission of the hole project to 755, to be sure it's not a problem with that, same results though.

Any ideas?

**Comment by dannyvankooten** [comment]
Does your server add trailing slashes `/` perhaps?

**Comment by mxdpeep** [comment]
> I'm just developing a little WebApp with PHP.
> 
> So far, I was only developing and testing offline, so on my localhost. Now, to see the behaviour on a server, I uploaded my code, fixed the database connection to fit for the MySQL-Server running on the server (which is Ubuntu 14.04) and tried to get it started.
> 
> First, what I'm doing for the routing, is a simple .htaccess, looking like that:
> 
> ```
> RewriteEngine On
> RewriteBase /
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteRule . /index.php [L] 
> ```
> 
> And then, in my index.php, the routing is done
> 
> ```
> <?php 
> 
> include 'vendor/altorouter/altorouter/AltoRouter.php';
> 
> $router = new AltoRouter();
> $router->setBasePath('');
> 
> $router->map('GET','/','home.php','home');
> $router->map('GET','/datenschutz','datenschutz.php','datenschutz');
> $router->map('GET','/impressum','impressum.php','impressum');
> 
> $router->map('GET','/header','header.php','header');
> $router->map('GET','/jquery','vendor/components/jquery/jquery.js','jquery');
> $router->map('GET','/bootstrapjs','vendor/twbs/bootstrap/dist/js/bootstrap.js','bootstrapjs');
> $router->map('GET','/bootstrapcss','vendor/twbs/bootstrap/dist/css/bootstrap.css','bootstrapcss');
> $router->map('GET','/generalStyle','style.css','generalStyle');
> $match = $router->match();
> if($match) {
>   if($match['name'] === 'generalStyle'){
>     header("Content-Type: text/css");
>     $fileName = $match['target'];
>     echo file_get_contents($fileName);
>     return;
>   }
>   require $match['target'];
> }
> else {
>   header("HTTP/1.0 404 Not Found");
>   require '404.php';
> }
> 
> ?>
> ```
> 
> This is perfectly working on my localhost, so there doesn't appear to be a problem in general.
> 
> However, on my server, when heading forward to the IP, it first seems, that it's working, because when only going to /, the home.php file is loaded correctly. But, whatever other route I call, like /impressum, it's not working, going back to /, the home.php is working again.
> 
> Now, replacing home.php (in the route) with impressum.php is working as well, then I can see the correct file as well. --> It's always only the "/" route, that's working...
> 
> Does anybody have an idea, why this happens or what the problem is?
> 
> I tried to call the files directly, and (besides some scripts not loaded etc.) its working, so going to myDomain.com/impressum.php is working fine, so it doesn't seem to be a problem of the file or sth.
> 
> I also tried to set the permission of the hole project to 755, to be sure it's not a problem with that, same results though.
> 
> Any ideas?

I have solved this by creating two routes with and w/o slash in the end of the path
