### ISSUE TITLE
Xampp 

### ISSUE THREAD

**Issue by romather** [dannyvankooten/AltoRouter#232]
Hello, friends!
I've using xampp for developing my app, and using altorouter but
``$router->map('GET', '/', function(){ require __DIR__ . '/../views.home.php; });``
don't redirect to home.php file!!! redirect to localhost/dashboard!! 
What's problem?

**Comment by Remzi1993** [comment]
This is not a problem with this library/project. It's XAMPP default files in C:\xampp\htdocs
Delete this first and then continue

**Comment by koenpunt** [comment]
As mentioned, please first check your xampp installation. Then after, make sure to follow the steps on http://altorouter.com/ which should guide you on how to use this library.
