### ISSUE TITLE
Is PHP 5.3 supported ?

### ISSUE THREAD

**Issue by coder966** [dannyvankooten/AltoRouter#237]
Hi. I personally don't think support for PHP < 5.6 is needed nowadays. but the website and README file say it does support PHP 5.3.

However, I don't see build tests for PHP < 5.6 and also the composer file says it requires PHP 5.6. So if the library does not support PHP < 5.6 please update the docs accordingly.

**Comment by mxdpeep** [comment]
nobody should build apps using < 7.1
go for 7.3, don't use anything older! 🍀

**Comment by ellisgl** [comment]
I would say 7.2

**Comment by mxdpeep** [comment]
> I would say 7.2

PHP 7.4, the next PHP 7 minor release, is expected to be released to the General Availability on November 28th, 2019

**Comment by mxdpeep** [comment]
![image](https://user-images.githubusercontent.com/75358/64912711-473d1480-d733-11e9-97d9-adf2443bfd56.png)

**Comment by dannyvankooten** [comment]
Hey, good catch and I totally agree that nobody should be on PHP 5.x at this point in time. Just updated the README to state PHP 5.6 as a hard-requirement with many links to the [supported PHP versions page](https://secure.php.net/supported-versions.php) as people should really be on a supported version. Thanks for the heads up!
