### ISSUE TITLE
Group routes with prefix

### ISSUE THREAD

**Issue by da-production** [dannyvankooten/AltoRouter#240]
how can i use group with prefix

**Comment by dannyvankooten** [comment]
There's no code for this in AltoRouter so it's totally up to you. I think it really doesn't save that much time nor does it make things much clearer, so I recommend a simple solution with some repetition:

```php
$router->map('GET', '/users/new');
$router->map('GET', '/users/[i:id]');
etc..
```

Alternatively:

```php
$prefix = '/users';
$router->map('GET', "$prefix/new");
$router->map('GET', "$prefix/[i:id]");
etc..
```

**Comment by da-production** [comment]
Hi,
Thank you for your help
:)
