### ISSUE TITLE
Form validator

### ISSUE THREAD

**Issue by BaptChau** [dannyvankooten/AltoRouter#242]
Hello everyone sorry if my english isn't good i'm french and i'm not fluent.

So i've got a project that you can found on github at https://github.com/BaptChau/Site_mjv.
I have some form in this project and when i wamt to submit it even with a route for the action nothing but errors append.
Did someone got any kind of solution please ?

Thanks

**Comment by dannyvankooten** [comment]
Did you map the route for the form action too? For example, when the form has `<form method="POST">` you should make sure that your route is also accepting `POST` requests.
