### ISSUE TITLE
Router can't find controller

### ISSUE THREAD

**Issue by leargon** [dannyvankooten/AltoRouter#243]
Should i write dependecies in my site controller:

This is route:
$router->map( 'GET', '/', 'SiteController#index' );

This is my controller:

namespace Civil;

class SiteController
{
	
	function index()
	{
		 echo 'Hello, autoloaded world!';
	}
}

i get 404 error

**Comment by koenpunt** [comment]
AltoRouter doesn't automagically call any method. You have to implement that yourself. Have a look at https://altorouter.org for usage instructions.
