### ISSUE TITLE
AltoRouter.com is down

### ISSUE THREAD

**Issue by tjw218** [dannyvankooten/AltoRouter#252]
You may alread know but it appears that AltoRouter.com is no longer resolving correctly.

```
This site can’t be reached
altorouter.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by dannyvankooten** [comment]
Hey, I didn't know it but it doesn't seem to be the case for me when I check it now? Works fine for me... Let me know if the issue persists please.
