### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by mp3000mp** [dannyvankooten/AltoRouter#253]
Hi,

I don't see any way to deal with "405 Method Not Allowed" http error.

```php
$match = $router->match();

if($match !== false) {
    var_dump($match);
}else{
    echo '404'; // or is it 405 ???
}
```

If there is no way as I assume, is it something you would like to implement ? 
If yes, how would you implement it ? I volunteer to do the pull request.

**Comment by bberneker-ikea** [comment]
header( $_SERVER["SERVER_PROTOCOL"] . ' 404 Not Found');

**Comment by mp3000mp** [comment]
Thanks, but the question is : when $match === false, do we have any way to know if we're dealing with a 404 or a 405 errors ?

**Comment by bberneker-ikea** [comment]
That's a question of your application logic.
404 Means a resource was not found, so no match would logically lead to a 404.
405 Means a method was not allowed, so if you literally mean request method, (i.e. GET, POST) you might want to try mapping your routes in groups by method and then handling them.

```
$router = new AltoRouter();
$router->map( 'GET', '/', function() { .. }, 'home' );
$match_GET = $router->match();
$router->map( 'POST', '/', function() { .. }, 'home' );
$match_POST = $router->match();

```
and then process each of the method matches in turn.

**Comment by bberneker-ikea** [comment]
You could also just check the request method directly:

```
if ($_SERVER['REQUEST_METHOD'] == "POST") {
    // do the thing
}
```

**Comment by mp3000mp** [comment]
Thanks a lot, I guess this is an acceptable turnover.
