### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by amt925** [dannyvankooten/AltoRouter#258]
Can we get a new release with the latest merge [247](https://github.com/dannyvankooten/AltoRouter/pull/247)?

**Comment by HexMakina** [comment]
> Can we get a new release with the latest merge [247](https://github.com/dannyvankooten/AltoRouter/pull/247)?

**Comment by vinkla** [comment]
I'm currently seeing the `Warning: Uninitialized string offset -1 in` issue which was fixed by #247. I'm also wondering if you could release a new version. If not, I maintain several big PHP projects and would be happy to help out pushing out new releases with this package.

**Comment by joelambert** [comment]
Any update on a release for this issue?

**Comment by dannyvankooten** [comment]
Hey everyone, sorry for the delay. 2.0.2 just released!

**Comment by vinkla** [comment]
Thanks Danny!

**Comment by joelambert** [comment]
Thanks @dannyvankooten. The `2.0.2` tag doesn't appear to be showing up on Packagist yet. 

https://packagist.org/packages/altorouter/altorouter

Just checking it's auto-updating ok from the repo?

**Comment by HexMakina** [comment]
Thanks @dannyvankooten

**Comment by amt925** [comment]
Thank you @dannyvankooten!
