### ISSUE TITLE
CURL in Altorouter function calls twice

### ISSUE THREAD

**Issue by TechOverflow** [dannyvankooten/AltoRouter#259]
I have a router similar to the example given:

```
$router->map('GET|POST', '/users/[i:id]/', function($id) {
  $user = .....
  require __DIR__ . '/views/user/details.php';
}, 'user-details');
```

My problem is that when I add a CURL call to this function, the CURL call happens twice and I have no idea why.
If I simply echo some text, it happens only once.
Anyone know what could be going on?

**Comment by koenpunt** [comment]
What do you mean with "add a CURL call"?

**Comment by TechOverflow** [comment]
Sorry, the fault was on the side of there server being called with CURL.
