### ISSUE TITLE
optional / in rule without any parameter

### ISSUE THREAD

**Issue by aliazizi** [dannyvankooten/AltoRouter#266]
In previous version if you put `/?` at end of the rule it work as optional `/` at end of url

But now its not working

I guess its because of this line
https://github.com/dannyvankooten/AltoRouter/blob/f6fede4f94ced7c22ba63a9b8af0bf2dc38e3cb2/AltoRouter.php#L231

Since in the route I dont have any `[` and I only use `?` for optional `/` this if is always true and it only check without regex/

**Comment by ThijmenDF** [comment]
Hi,

Trailing slashes can be made optional by using `[/?]` at the end of your configured URL. 

Here are some examples:
| Url | `/contact` | `/contact[/?]` | `/contact/[i:id]?` | `/contact/[i:id]?[/?]` |
| --- | --- | --- | --- | --- |
| `/contact` | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: * | :heavy_multiplication_x: |
| `/contact/` |  | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: |
| `/contact/32` |  |  | :heavy_multiplication_x: | :heavy_multiplication_x: |
| `/contact/32/` | | | | :heavy_multiplication_x: |
| `/contact/32//` | | | | |
 
(*) Optional parameters' trailing slashes are filtered here:
https://github.com/dannyvankooten/AltoRouter/blob/master/AltoRouter.php#L237

I hope this helps clear things up a little.
