### ISSUE TITLE
preg_match(): Compilation failed, PCRE2_DUPNAMES not set

### ISSUE THREAD

**Issue by xpetter** [dannyvankooten/AltoRouter#267]
PHP Warning:  preg_match(): Compilation failed: two named subpatterns have the same name (PCRE2_DUPNAMES not set) at offset 36 in AltoRouter.php on line 242

Running on PHP 8.1

It seems that the error occurs when there is no match

**Comment by dannyvankooten** [comment]
Hello @xpetter,

I think this depends on your registered routes. Could it be that you have a route where you named two parameters but gave them the same name?

**Comment by xpetter** [comment]
Yes, I found it now, sorry my mistake.

**Comment by dannyvankooten** [comment]
Glad that was it @xpetter. Thanks for chiming in!
