### ISSUE TITLE
External file for routes

### ISSUE THREAD

**Issue by kamov** [dannyvankooten/AltoRouter#54]
Hi,

Is possible add external file (example .ini file) with all routes, something like:

[routes]
home="GET|POST /home home#index"
users="GET /users users#index"

then when we create new instance we can:

$router = new AltoRouter('routes.ini');

$match = $router->match();

Thanks!!

**Comment by koenpunt** [comment]
To use a custom route file you'll have to write an extension of AltoRouter yourself.
