### ISSUE TITLE
example for actually calling controller#action and passing vars?

### ISSUE THREAD

**Issue by unitedworx** [dannyvankooten/AltoRouter#57]
hi there, just played a bit with AltoRouter and figured out that it leaves out to me to actually call the matched controller#action and pass the appropriate vars but i am not sure i implemented this correctly. it surely works but thought of making sure i am on the correct route :) you might want to include this in an example if this is the correct way of doing this to help others 

```php
$router = new AltoRouter();
$router->setBasePath('/demosite4.com'); 
$router->map('GET','/', 'home_controller#display_item', 'home');
$router->map('GET','/content/[:parent]/?[:child]?', 'content_controller#display_item', 'content');
$match = $router->match();

// not sure if code after this comment  is the best way to handle matched routes
list( $controller, $action ) = explode( '#', $match['target'] );
if ( is_callable(array($controller, $action)) ) {
	$obj = new $controller();
	call_user_func_array(array($obj,$action), array($match['params']));
} else if ($match['target']==''){
	echo 'Error: no route was matched'; 
	//possibly throw a 404 error
} else {
	echo 'Error: can not call '.$controller.'#'.$action; 
	//possibly throw a 404 error
}


// content_controller class file is autoloaded 
 <?php
class content_controller {
	public function display_item($args) {
		//echo our params to to make sure we got them
		echo 'parent: '. $args['parent'];
		echo 'child: '. $args['child'];
	}
?>
```

**Comment by ysupr** [comment]
hi @niahoo and @unitedworx then how you managed to autoload class? rather than using include one by one classes ?

**Comment by niahoo** [comment]
Well, I define my application in a composer package and define PSR-4 mapping in composer.json so the composer autoloader handles this for me :)

**Comment by koenpunt** [comment]
Submit new issues to request additional documentation.

**Comment by Hexodus** [comment]
@niahoo Thanks for sharing your code but I found a typo in this line:

    call_user_func_array(array($obj,$action), array($match['params']));

This should be: 

    call_user_func_array(array($controller,$action), array($match['params']));

Because the $obj variable isn't defined.

I also strongly recommend to catch the error in case when the controller does not exist: 

        if(call_user_func_array(array($controller, $action), array($match['params'])) === false)
        {
        	//error handling here when controller could not be found
        }

**Comment by niahoo** [comment]
This is an old one but yeah it's a copy/paste error, I've edited my post.

As for the error handling, I prefer let it crash. It makes no sense to define a route to a controller/action couple that don't exist. This error should not be handled at this level.

Either at an upper level you handle app-wide exceptions or you just don't handle this case since you just route to things that exist. Write defensive code as less as possible :)
